---
title: "Untitled"
author: "Brandon L. Kramer"
date: "10/18/2020"
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls())
for (pkg in c( "tidyverse", "janitor", 
               "cowplot", "hrbrthemes")) {library(pkg, character.only = TRUE)}
source("~/Documents/fantasy-basketball/funs/nba_team_abbs.R")
source("~/Documents/fantasy-basketball/funs/conv_to_points.R")
nba_player_data_raw <- read_rds("~/Documents/fantasy-basketball/data/nba_player_data/nba_player_season/nba_stats_19502019.Rds")

# clean the data 
nba_player_data <- nba_player_data_raw %>% 
  clean_nba_names(player) %>% 
  bbrhist_avgs_to_fppg()

# ranking the top ld/franchise seasons ever 
ld_ranked_seasons <- nba_player_data %>% 
  arrange(-ld_fppg_bbr) %>% 
  filter(mp > 500) %>%
  select(year, player, pos, age, tm, contains("fppg")) %>% 
  drop_na(ld_fppg_bbr, fr_fppg_bbr, botb_fppg_bbr, gsd2_fppg_bbr)

# remove all the duplicates (when trades happen)
ld_ranked_seasons %>% 
  get_dupes(player, age) %>% 
  filter(tm == "TOT") 
```

```{r, fig.width=10, fig.height=4}
ggplot(ld_ranked_seasons, aes(ld_fppg_bbr)) +
  geom_histogram(binwidth = 0.2) +
  theme_minimal() +
  ggtitle("Distribution of Points Per Game for Player with 500+ minutes (1980-2019)") 
```
```{r}
count <- ld_ranked_seasons %>% count()
df60 <- ld_ranked_seasons %>% 
  filter(ld_fppg_bbr > 60) %>% count() %>% 
  mutate(perc_over = n / count$n, threshold = 60)
df50 <- ld_ranked_seasons %>% 
  filter(ld_fppg_bbr > 50) %>% count() %>% 
  mutate(perc_over = n / count$n, threshold = 50)
df40 <- ld_ranked_seasons %>% 
  filter(ld_fppg_bbr > 40) %>% count() %>% 
  mutate(perc_over = n / count$n, threshold = 40)
df30 <- ld_ranked_seasons %>% 
  filter(ld_fppg_bbr > 30) %>% count() %>% 
  mutate(perc_over = n / count$n, threshold = 30)
df20 <- ld_ranked_seasons %>% 
  filter(ld_fppg_bbr > 20) %>% count() %>% 
  mutate(perc_over = n / count$n, threshold = 20)
over_threshold <- rbind(df60, df50, df40, df30, df20)
over_threshold <- over_threshold %>% select(threshold, perc_over, n)
rm(count, df60, df50, df40, df30, df20)
over_threshold
```

```{r, fig.width=10, fig.height=4}
var_by_age <- ggplot(ld_ranked_seasons, aes(age, ld_fppg_bbr)) +
  geom_point() + 
  theme_minimal() +
  ggtitle("Distribution of All Totals by Age")

mean_by_age <- ld_ranked_seasons %>% 
  filter(ld_fppg_bbr > 20) %>%
  select(age, ld_fppg_bbr) %>% 
  arrange(age) %>% 
  mutate(age = as.factor(age))

mean_by_age <- ggplot(mean_by_age, aes(x=age, y=ld_fppg_bbr)) + 
  geom_boxplot() +
  theme_minimal() +
  ggtitle("Mean & SD by Age")

plot_grid(var_by_age, mean_by_age, label_size = 12)
```
```{r}
age19 <- ld_ranked_seasons %>% 
  filter(age == 19) %>% select(player, ld_fppg_bbr) %>% rename(fppg_at_19 = ld_fppg_bbr)
age20 <- ld_ranked_seasons %>% 
  filter(age == 20) %>% select(player, ld_fppg_bbr) %>% rename(fppg_at_20 = ld_fppg_bbr)
age21 <- ld_ranked_seasons %>% 
  filter(age == 21) %>% select(player, ld_fppg_bbr) %>% rename(fppg_at_21 = ld_fppg_bbr)
age22 <- ld_ranked_seasons %>% 
  filter(age == 22) %>% select(player, ld_fppg_bbr) %>% rename(fppg_at_22 = ld_fppg_bbr)
rookie_production <- age19 %>% 
  full_join(age20, by = "player") %>% 
  full_join(age21, by = "player") %>% 
  full_join(age22, by = "player") %>% 
  mutate(diff1922 = fppg_at_22 - fppg_at_19) %>%
  mutate(diff1920 = fppg_at_20 - fppg_at_19) %>% 
  mutate(diff2021 = fppg_at_21 - fppg_at_20) %>% 
  mutate(diff2122 = fppg_at_22 - fppg_at_21) %>%
  mutate(diff1921 = fppg_at_21 - fppg_at_19) %>%
  mutate(diff2022 = fppg_at_22 - fppg_at_20) %>% 
  arrange(-diff1922) %>% 
  distinct(player, fppg_at_19, fppg_at_20, fppg_at_21, fppg_at_22,
           diff1922, diff2021, diff2122, diff1921, diff2022)

rookie_production %>% 
  distinct(player, fppg_at_19) %>% 
  arrange(-fppg_at_19)
```
```{r}
production_over_time <- rookie_production %>% 
  filter(fppg_at_19 > 15 & fppg_at_20 > 20 | fppg_at_21 > 30 | fppg_at_22 > 40) %>% 
  select(-starts_with("diff")) %>%
  pivot_longer(!player, names_to = "age", values_to = "fppg") %>% 
  mutate(age = str_replace_all(age, "fppg_at_19", "19"),
         age = str_replace_all(age, "fppg_at_20", "20"),
         age = str_replace_all(age, "fppg_at_21", "21"),
         age = str_replace_all(age, "fppg_at_22", "22"),
         age = as.numeric(age))

ggplot(data = production_over_time, aes(x = age, y = fppg))+
  geom_line(aes(color = player), size = 1) + 
  theme_minimal() +
  theme(legend.position="none")
```





```{r}
botb_ranked_seasons <- nba_player_data %>% 
  arrange(-botb_fppg_bbr) %>% 
  select(year, player, pos, age, tm, contains("fppg")) %>% 
  drop_na(ld_fppg_bbr, fr_fppg_bbr, botb_fppg_bbr, gsd2_fppg_bbr)
botb_ranked_seasons
```







```{r}

cor(ranked_seasons %>% select(age, ld_fppg_bbr, botb_fppg_bbr))

```
























