---
title: "The Invitational Fantasy Tools"
author: "Brandon L. Kramer"
date: "9/2/2019"
output: html_document
---

This file contains the following materials for Legacy Dynasty NBA fantasy points league 

* Concatenation of Basketball Reference (2018), Hashtag (2019), and Hashtag Alt (2019) Projections
* Overall Stats and Projections
* Team Projections
* Team Players Quick Comparisons 
* Post-Trade Comparison Tool 

```{r pull packages and projection data}
#install.packages("tidyverse"); install.packages("googlesheets")
rm(list = ls())
for (pkg in c("googlesheets", "tidyverse")) {library(pkg, character.only = TRUE)}
(my_sheets <- gs_ls())

bballref18 <- gs_url("https://docs.google.com/spreadsheets/d/13EnBmUWDmxJ86xFzCpaHUuXGW0KADW_bDUVLf0dWFgA/edit#gid=58340951") %>% 
  gs_read(ws = "bballref18") 

bballref18$player <- bballref18$player %>% 
  str_replace_all(c('Á' = 'A', 'ā' = 'a', 'á' = 'a', 'č' = 'c', 'ć' = 'c', 'è' = 'e', 
                    'é' = 'e', 'ê' = 'e', 'ić' = 'ic', 'ö' = 'o', 'ó' = 'o', 'Š' = 'S', 
                    'š' = 's', 'ū' = 'u', 'ý' = 'y', 'Ž' = 'Z', 'ž' = 'z', 
                    'Élie' = 'Elie','P.J.' = 'PJ','C.J.' = 'CJ', 'R.J.' = 'RJ', 'T.J.' = 'TJ', 
                    'D.J.' = 'DJ', 'J.J.' = 'JJ', 'Dončić' = 'Doncic', 'Louis' = 'Lou', 'Edrice' = 'Bam', 
                    'Waller-Prince' = 'Prince', "O.G." = "OG", "Demarre" = "DeMarre",
                    'Jaren Jackson' = 'Jaren Jackson Jr.','Kelly Oubre' = 'Kelly Oubre Jr.', 
                    'Marvin Bagley' = 'Marvin Bagley III', 'Otto Porter' = 'Otto Porter Jr.', 
                    'Wendell Carter' = 'Wendell Carter Jr.', 'Larry Nance' = 'Larry Nance Jr.',
                    'Walt Lemon' = 'Walt Lemon Jr.', 'Dennis Schröder' = 'Dennis Schroder', 
                    'Tim Hardaway' = 'Tim Hardaway Jr.'))

combined_data <- bballref18 %>% 
  rename(bbr_pts = "PTS", bbr_dreb = "DRB", bbr_orb = "ORB",
         bbr_ast = "AST", bbr_stl = "STL", bbr_blk = "BLK",
         bbr_tov = "TOV", bbr_threes = "3P", bbr_fga = "FGA",
         bbr_fgm = "FG", bbr_ftm = "FT",  bbr_fta = "FTA", 
         bbr_gms = "G", bbr_mpg = "MP", age = "Age", bbr_fgp = "FG%", bbr_ftp = "FT%") %>%
  mutate(bbr_treb = bbr_dreb + bbr_orb) %>% 
  mutate(bbr_ld_fpts = bbr_pts + (bbr_dreb*1.5) + (bbr_orb*2) + (bbr_ast*2) + (bbr_stl*2.5) + (bbr_blk*2.5) +
         (bbr_tov*-1) + bbr_threes + (bbr_fga*-0.5) + (bbr_fgm*0.5) + bbr_ftm + (bbr_fta*-1)) %>%
  mutate(bbr_fr_fpts = bbr_pts + (bbr_dreb*1.5) + (bbr_orb*2) + (bbr_ast*2) + (bbr_stl*2.5) + (bbr_blk*2.5) +
         (bbr_tov*-1) + bbr_threes + (bbr_fga*-0.5) + (bbr_fgm*0.5) + bbr_ftm + (bbr_fta*-1)) %>% 
  mutate(bbr_gsd2_fpts = bbr_pts + bbr_dreb + (bbr_orb*1.25) + (bbr_ast*1.5) + (bbr_stl*1.5) + (bbr_blk*2) +
         (bbr_tov*-1)+bbr_threes+(bbr_fga*-0.5)+(bbr_fgm*0.5)+(bbr_ftm*0.5)+(bbr_fta*-0.75)) %>%
  mutate(bbr_botb_fpts = bbr_pts + bbr_dreb + (bbr_orb*1.25) + (bbr_ast*1.5) + (bbr_stl*1.5) + (bbr_blk*2) +
         (bbr_tov*-1)+bbr_threes+(bbr_fga*-0.5)+(bbr_fgm*0.5)+(bbr_ftm*0.5)+(bbr_fta*-0.75)) %>% 
  select(player, age, bbr_ld_fpts, bbr_fr_fpts, bbr_gsd2_fpts, bbr_botb_fpts, bbr_gms, bbr_mpg,
         bbr_pts, bbr_treb, bbr_ast, bbr_stl, bbr_blk, bbr_tov, bbr_threes, 
         bbr_fga, bbr_fgm, bbr_ftm, bbr_fta, bbr_fgp, bbr_ftp, bbr_dreb, bbr_orb)

hashtag19 <- gs_url("https://docs.google.com/spreadsheets/d/13EnBmUWDmxJ86xFzCpaHUuXGW0KADW_bDUVLf0dWFgA/edit#gid=665288709") %>% gs_read(ws = "2019_hashtag_proj") 

hashtag19$player <- hashtag19$player %>% 
  str_replace_all(c('Á' = 'A', 'ā' = 'a', 'á' = 'a', 'č' = 'c', 'ć' = 'c', 'è' = 'e', 'é' = 'e', 'ê' = 'e',
                    'ö' = 'o', 'ó' = 'o', 'Š' = 'S', 'š' = 's', 'ū' = 'u', 'ý' = 'y', 'Ž' = 'Z', 'ž' = 'z',
                    'P.J.' = 'PJ','C.J.' = 'CJ', 'R.J.' = 'RJ', 'T.J.' = 'TJ', 'D.J.' = 'DJ', 'J.J.' = 'JJ',
                    'Louis' = 'Lou', 'Edrice' = 'Bam', 'Waller-Prince' = 'Prince', "O.G." = "OG", 
                    "Demarre" = "DeMarre",'Dennis Schröder' = 'Dennis Schroder'))

hashtag19 <- hashtag19 %>% 
  rename(ht_pts = "PTS", ht_dreb = "DREB", ht_orb = "OREB", ht_ast = "AST", ht_stl = "STL", ht_blk = "BLK",
         ht_tov = "TO", ht_threes = "THREES", ht_fga = "FGA", ht_fgm = "FGM", ht_ftm = "FTM",  
         ht_fta = "FTA", ht_mpg = "MPG", ht_gms = "GP", ht_fgp = "FG%", ht_ftp = "FT%") %>%
  mutate(ht_treb = ht_dreb + ht_orb) %>%
  mutate(ht_ld_fpts = ht_pts + (ht_dreb*1.5) + (ht_orb*2) + (ht_ast*2) + (ht_stl*2.5) + (ht_blk*2.5) +
         (ht_tov*-1) + ht_threes + (ht_fga*-0.5) + (ht_fgm*0.5) + ht_ftm + (ht_fta*-1)) %>%
  mutate(ht_fr_fpts = ht_pts + (ht_dreb*1.5) + (ht_orb*2) + (ht_ast*2) + (ht_stl*2.5) + (ht_blk*2.5) +
         (ht_tov*-1) + ht_threes + (ht_fga*-0.5) + (ht_fgm*0.5) + ht_ftm + (ht_fta*-1)) %>% 
  mutate(ht_gsd2_fpts = ht_pts + ht_dreb + (ht_orb*1.25) + (ht_ast*1.5) + (ht_stl*1.5) + (ht_blk*2) +
         (ht_tov*-1)+ht_threes+(ht_fga*-0.5)+(ht_fgm*0.5)+(ht_ftm*0.5)+(ht_fta*-0.75)) %>%
  mutate(ht_botb_fpts = ht_pts + ht_dreb + (ht_orb*1.25) + (ht_ast*1.5) + (ht_stl*1.5) + (ht_blk*2) +
         (ht_tov*-1)+ht_threes+(ht_fga*-0.5)+(ht_fgm*0.5)+(ht_ftm*0.5)+(ht_fta*-0.75)) %>% 
  select(player, ht_ld_fpts, ht_fr_fpts, ht_gsd2_fpts, ht_botb_fpts, ht_gms, ht_mpg, 
         ht_pts, ht_treb, ht_ast, ht_stl, ht_blk, ht_tov, ht_threes, 
         ht_fga, ht_fgm, ht_fgp, ht_ftm, ht_fta, ht_ftp, ht_dreb, ht_orb)

combined_data <- combined_data %>% 
  full_join(hashtag19, by = "player")

hashalt19 <- gs_url("https://docs.google.com/spreadsheets/d/13EnBmUWDmxJ86xFzCpaHUuXGW0KADW_bDUVLf0dWFgA/edit#gid=2083425618") %>% gs_read(ws = "2019_hashtag_alt_proj") 

hashalt19$player <- hashalt19$player %>% 
  str_replace_all(c('Á' = 'A', 'ā' = 'a', 'á' = 'a', 'č' = 'c', 'ć' = 'c', 'è' = 'e', 'é' = 'e', 'ê' = 'e',
                    'ö' = 'o', 'ó' = 'o', 'Š' = 'S', 'š' = 's', 'ū' = 'u', 'ý' = 'y', 'Ž' = 'Z', 'ž' = 'z',
                    'P.J.' = 'PJ','C.J.' = 'CJ', 'R.J.' = 'RJ', 'T.J.' = 'TJ', 'D.J.' = 'DJ', 'J.J.' = 'JJ',
                    'Louis' = 'Lou', 'Edrice' = 'Bam', 'Waller-Prince' = 'Prince', "O.G." = "OG", 
                    'Jaren Jackson' = 'Jaren Jackson Jr.','Kelly Oubre' = 'Kelly Oubre Jr.', 
                    'Marvin Bagley' = 'Marvin Bagley III', 'Otto Porter' = 'Otto Porter Jr.', 
                    'Wendell Carter' = 'Wendell Carter Jr.', 'Larry Nance' = 'Larry Nance Jr.',
                    'Walt Lemon' = 'Walt Lemon Jr.', 'Dennis Schröder' = 'Dennis Schroder', 
                    'Tim Hardaway' = 'Tim Hardaway Jr.', "Demarre" = "DeMarre"))

hashalt19 <- hashalt19 %>% 
  rename(hta_pts = "PTS", hta_treb = "REB", hta_ast = "AST", hta_stl = "STL", hta_blk = "BLK",
         hta_tov = "TOV", hta_threes = "THREES", hta_fga = "FGA", hta_fgm = "FGM", hta_ftm = "FTM",  
         hta_fta = "FTA", hta_mpg = "MPG", hta_ftp = "FT", hta_fgp = "FG", hta_gms = "Gs") %>%
  mutate(hta_dreb = hta_treb*0.78) %>% 
  mutate(hta_orb = hta_treb*0.22) %>% 
  mutate(hta_ld_fpts = hta_pts + (hta_dreb*1.5) + (hta_orb*2) + (hta_ast*2) + (hta_stl*2.5) + (hta_blk*2.5) +
         (hta_tov*-1) + hta_threes + (hta_fga*-0.5) + (hta_fgm*0.5) + hta_ftm + (hta_fta*-1)) %>%
  mutate(hta_fr_fpts = hta_pts + (hta_dreb*1.5) + (hta_orb*2) + (hta_ast*2) + (hta_stl*2.5) + (hta_blk*2.5) +
         (hta_tov*-1) + hta_threes + (hta_fga*-0.5) + (hta_fgm*0.5) + hta_ftm + (hta_fta*-1)) %>% 
  mutate(hta_gsd2_fpts = hta_pts + hta_dreb + (hta_orb*1.25) + (hta_ast*1.5) + (hta_stl*1.5) + (hta_blk*2) +
         (hta_tov*-1)+hta_threes+(hta_fga*-0.5)+(hta_fgm*0.5)+(hta_ftm*0.5)+(hta_fta*-0.75)) %>%
  mutate(hta_botb_fpts = hta_pts + hta_dreb + (hta_orb*1.25) + (hta_ast*1.5) + (hta_stl*1.5) + (hta_blk*2) +
         (hta_tov*-1)+hta_threes+(hta_fga*-0.5)+(hta_fgm*0.5)+(hta_ftm*0.5)+(hta_fta*-0.75)) %>% 
  select(player, hta_ld_fpts, hta_fr_fpts, hta_gsd2_fpts, hta_botb_fpts, hta_gms, hta_mpg, 
         hta_pts, hta_treb, hta_ast, hta_stl, hta_blk, hta_tov, hta_threes, 
         hta_fga, hta_fgm, hta_ftm, hta_fta, hta_ftp, hta_fgp, hta_dreb, hta_orb)
  
combined_data <- combined_data %>% 
  full_join(hashalt19, by = "player")

the_invitational <- gs_url("https://docs.google.com/spreadsheets/d/13EnBmUWDmxJ86xFzCpaHUuXGW0KADW_bDUVLf0dWFgA/edit#gid=1960421065") %>% gs_read(ws = "the_invitational")

the_invitational$player <- the_invitational$player %>% 
  str_replace_all(c('C.J.' = 'CJ', 'R.J.' = 'RJ', 'T.J.' = 'TJ', 'D.J.' = 'DJ', "O.G." = "OG", "Demarre" = "DeMarre",
                    'Louis' = 'Lou', 'Edrice' = 'Bam', 'Waller-Prince' = 'Prince', 
                    'Á' = 'A', 'ā' = 'a', 'á' = 'a', 'č' = 'c', 'ć' = 'c', 'è' = 'e', 'é' = 'e', 'ê' = 'e',
                    'ö' = 'o', 'ó' = 'o', 'Š' = 'S', 'š' = 's', 'ū' = 'u', 'ý' = 'y', 'Ž' = 'Z', 'ž' = 'z',
                    'P.J.' = 'PJ','C.J.' = 'CJ', 'R.J.' = 'RJ', 'T.J' = 'TJ', 'D.J.' = 'DJ', 'J.J.' = 'JJ'))

combined_data <- combined_data %>% 
  full_join(the_invitational, by = "player")

select_data <- combined_data %>% 
  select(player, age, 
         bbr_pts, bbr_treb,  bbr_ast, bbr_stl, bbr_blk, bbr_tov, bbr_threes, 
         bbr_fga, bbr_fgm,   bbr_ftm, bbr_fta, bbr_gms, bbr_mpg, bbr_fgp, bbr_ftp, bbr_dreb, bbr_orb,
         ht_pts,  ht_treb,   ht_ast,  ht_stl,  ht_blk,  ht_tov,  ht_threes, 
         ht_fga,  ht_fgm,    ht_ftm,  ht_fta,  ht_mpg,  ht_gms,  ht_fgp,  ht_ftp, ht_dreb,  ht_orb,
         hta_pts, hta_treb,  hta_ast, hta_stl, hta_blk, hta_tov, hta_threes,  
         hta_fga, hta_fgm,   hta_ftm, hta_fta, hta_mpg, hta_fgp, hta_ftp, hta_gms, hta_dreb, hta_orb, 
         inv_team, inv_abbreviated, trade_comp)
rm(bballref18, hashtag19, hashalt19, the_invitational, my_sheets)
```


```{r looking at projections by cat in bbr stats}
select_data %>% 
#  filter(bbr_gms > 50) %>%
#  filter(bbr_mpg > 25) %>%
#  filter(age < 25) %>% 
  arrange(-bbr_pts) %>% 
#  arrange(-bbr_treb) %>% 
#  arrange(-bbr_ast) %>% 
#  arrange(-bbr_stl) %>% 
#  arrange(-bbr_blk) %>% 
#  arrange(-bbr_tov) %>% 
#  arrange(-bbr_threes) %>% 
#  arrange(-bbr_fgp) %>% 
#  arrange(-bbr_ftp) %>% 
  select(player, age, inv_team, bbr_pts, bbr_treb, bbr_ast, bbr_stl, bbr_blk, bbr_tov, bbr_threes, 
         bbr_fga, bbr_fgm,  bbr_fta, bbr_ftm, bbr_gms, bbr_mpg, bbr_fgp, bbr_ftp)
```
```{r looking at projections by cat in ht stats}
select_data %>% 
#  filter(ht_gms > 50) %>%
#  filter(ht_mpg > 25) %>%
#  filter(age < 25) %>% 
  arrange(-ht_pts) %>% 
#  arrange(-ht_treb) %>% 
#  arrange(-ht_ast) %>% 
#  arrange(-ht_stl) %>% 
#  arrange(-ht_blk) %>% 
#  arrange(-ht_tov) %>% 
#  arrange(-ht_threes) %>% 
#  arrange(-ht_fgp) %>% 
#  arrange(-ht_ftp) %>% 
  select(player, age, inv_team, ht_pts, ht_treb, ht_ast, ht_stl, ht_blk, ht_tov, ht_threes, 
         ht_fga, ht_fgm,  ht_fta, ht_ftm, ht_gms, ht_mpg, ht_fgp, ht_ftp, bbr_gms, bbr_mpg)
```

```{r looking at projections by cat in hta stats}
select_data %>% 
  filter(bbr_gms > 50) %>%
#  filter(hta_mpg > 25) %>%
#  filter(age < 25) %>% 
#  arrange(-hta_pts) %>% 
#  arrange(-hta_treb) %>% 
#  arrange(-hta_ast) %>% 
#  arrange(-hta_stl) %>% 
#  arrange(-hta_blk) %>% 
#  arrange(-hta_tov) %>% 
#  arrange(-hta_threes) %>% 
  arrange(-hta_fgp) %>% 
#  arrange(-hta_ftp) %>% 
  select(player, age, inv_team, hta_pts, hta_treb, hta_ast, hta_stl, hta_blk, hta_tov, hta_threes, 
         hta_fga, hta_fgm,  hta_fta, hta_ftm, hta_gms, hta_mpg, hta_fgp, hta_ftp, bbr_gms, bbr_mpg)
```

```{r}
inv_projections <- select_data %>% 
  group_by(inv_abbreviated) %>% 
  filter(inv_abbreviated != "") %>% 
  summarize(bbr_team_pts = sum(bbr_pts, na.rm = TRUE),
            bbr_team_rebs = sum(bbr_treb, na.rm = TRUE),
            bbr_team_asts = sum(bbr_ast, na.rm = TRUE),
            bbr_team_stls = sum(bbr_stl, na.rm = TRUE),
            bbr_team_blks = sum(bbr_blk, na.rm = TRUE),
            bbr_team_tovs = sum(bbr_tov, na.rm = TRUE),
            bbr_team_threes = sum(bbr_threes, na.rm = TRUE),
            bbr_team_fgp = (sum(bbr_fgm, na.rm = TRUE) / sum(bbr_fga, na.rm = TRUE)),  
            bbr_team_ftp = (sum(bbr_ftm, na.rm = TRUE) / sum(bbr_fta, na.rm = TRUE)),
            
            ht_team_pts = sum(ht_pts, na.rm = TRUE),
            ht_team_rebs = sum(ht_treb, na.rm = TRUE),
            ht_team_asts = sum(ht_ast, na.rm = TRUE),
            ht_team_stls = sum(ht_stl, na.rm = TRUE),
            ht_team_blks = sum(ht_blk, na.rm = TRUE),
            ht_team_tovs = sum(ht_tov, na.rm = TRUE),
            ht_team_threes = sum(ht_threes, na.rm = TRUE),
            ht_team_fgp = (sum(ht_fgm, na.rm = TRUE) / sum(ht_fga, na.rm = TRUE)), 
            ht_team_ftp = (sum(ht_ftm, na.rm = TRUE) / sum(ht_fta, na.rm = TRUE)), 
    
            hta_team_pts = sum(hta_pts, na.rm = TRUE),
            hta_team_rebs = sum(hta_treb, na.rm = TRUE),
            hta_team_asts = sum(hta_ast, na.rm = TRUE),
            hta_team_stls = sum(hta_stl, na.rm = TRUE),
            hta_team_blks = sum(hta_blk, na.rm = TRUE),
            hta_team_tovs = sum(hta_tov, na.rm = TRUE),
            hta_team_threes = sum(hta_threes, na.rm = TRUE),
            hta_team_fgp = (sum(hta_fgm, na.rm = TRUE) / sum(hta_fga, na.rm = TRUE)),
            hta_team_ftp = (sum(hta_ftm, na.rm = TRUE) / sum(hta_fta, na.rm = TRUE))) 

```

```{r hashtag rankings graphed, fig.width=11, fig.height=6, warning=FALSE}
# points 
ggplot(data=inv_projections, aes(x=reorder(inv_abbreviated, -ht_team_pts), y=ht_team_pts, fill=inv_abbreviated)) +
  geom_bar(stat="identity", width=0.6, colour="black") +
  geom_text(aes(label = ht_team_pts), size = 2.3, colour="black", fontface="bold", hjust = 0.5, vjust = 3) +
  theme_bw() +
  theme(axis.title.x=element_blank(), 
        axis.title.y=element_blank()) +
  labs(title = "The Invitational Rankings - Projected Team Points (Based on 2019 Hashtag)", fill = "Team")

# rebounds 
ggplot(data=inv_projections, aes(x=reorder(inv_abbreviated, -ht_team_rebs), y=ht_team_rebs, fill=inv_abbreviated)) +
  geom_bar(stat="identity", width=0.6, colour="black") +
  geom_text(aes(label = ht_team_rebs), size = 2.3, colour="black", fontface="bold", hjust = 0.5, vjust = 3) +
  theme_bw() +
  theme(axis.title.x=element_blank(), 
        axis.title.y=element_blank()) +
  labs(title = "The Invitational Rankings - Projected Team Rebounds (Based on 2019 Hashtag)", fill = "Team")

# assists 
ggplot(data=inv_projections, aes(x=reorder(inv_abbreviated, -ht_team_asts), y=ht_team_asts, fill=inv_abbreviated)) +
  geom_bar(stat="identity", width=0.6, colour="black") +
  geom_text(aes(label = ht_team_asts), size = 2.3, colour="black", fontface="bold", hjust = 0.5, vjust = 3) +
  theme_bw() +
  theme(axis.title.x=element_blank(), 
        axis.title.y=element_blank()) +
  labs(title = "The Invitational Rankings - Projected Team Assists (Based on 2019 Hashtag)", fill = "Team")

# steals 
ggplot(data=inv_projections, aes(x=reorder(inv_abbreviated, -ht_team_stls), y=ht_team_stls, fill=inv_abbreviated)) +
  geom_bar(stat="identity", width=0.6, colour="black") +
  geom_text(aes(label = ht_team_stls), size = 2.3, colour="black", fontface="bold", hjust = 0.5, vjust = 3) +
  theme_bw() +
  theme(axis.title.x=element_blank(), 
        axis.title.y=element_blank()) +
  labs(title = "The Invitational Rankings - Projected Team Steals (Based on 2019 Hashtag)", fill = "Team")

# blocks 
ggplot(data=inv_projections, aes(x=reorder(inv_abbreviated, -ht_team_blks), y=ht_team_blks, fill=inv_abbreviated)) +
  geom_bar(stat="identity", width=0.6, colour="black") +
  geom_text(aes(label = ht_team_blks), size = 2.3, colour="black", fontface="bold", hjust = 0.5, vjust = 3) +
  theme_bw() +
  theme(axis.title.x=element_blank(), 
        axis.title.y=element_blank()) +
  labs(title = "The Invitational Rankings - Projected Team Blocks (Based on 2019 Hashtag)", fill = "Team")

# turnovers 
ggplot(data=inv_projections, aes(x=reorder(inv_abbreviated, ht_team_tovs), y=ht_team_tovs, fill=inv_abbreviated)) +
  geom_bar(stat="identity", width=0.6, colour="black") +
  geom_text(aes(label = ht_team_tovs), size = 2.3, colour="black", fontface="bold", hjust = 0.5, vjust = 3) +
  theme_bw() +
  theme(axis.title.x=element_blank(), 
        axis.title.y=element_blank()) +
  labs(title = "The Invitational Rankings - Projected Team Turnovers (Based on 2019 Hashtag)", fill = "Team")

# threes 
ggplot(data=inv_projections, aes(x=reorder(inv_abbreviated, -ht_team_threes), y=ht_team_threes, fill=inv_abbreviated)) +
  geom_bar(stat="identity", width=0.6, colour="black") +
  geom_text(aes(label = ht_team_threes), size = 2.3, colour="black", fontface="bold", hjust = 0.5, vjust = 3) +
  theme_bw() +
  theme(axis.title.x=element_blank(), 
        axis.title.y=element_blank()) +
  labs(title = "The Invitational Rankings - Projected Team Threes (Based on 2019 Hashtag)", fill = "Team")

# fgp 
ggplot(data=inv_projections, aes(x=reorder(inv_abbreviated, -ht_team_fgp), y=ht_team_fgp, fill=inv_abbreviated)) +
  geom_bar(stat="identity", width=0.6, colour="black") +
  geom_text(aes(label = round(ht_team_fgp,digits=2)), size = 2.3, colour="black", fontface="bold", hjust = 0.5, vjust = 3) +
  theme_bw() +
  theme(axis.title.x=element_blank(), 
        axis.title.y=element_blank()) +
  labs(title = "The Invitational Rankings - Projected Team FG% (Based on 2019 Hashtag)", fill = "Team")

# ftp 
ggplot(data=inv_projections, aes(x=reorder(inv_abbreviated, -ht_team_ftp), y=ht_team_ftp, fill=inv_abbreviated)) +
  geom_bar(stat="identity", width=0.6, colour="black") +
  geom_text(aes(label = round(ht_team_ftp,digits=2)), size = 2.3, colour="black", fontface="bold", hjust = 0.5, vjust = 3) +
  theme_bw() +
  theme(axis.title.x=element_blank(), 
        axis.title.y=element_blank()) +
  labs(title = "The Invitational Rankings - Projected Team FG% (Based on 2019 Hashtag)", fill = "Team")

```





```{r hashtag alt rankings graphed, fig.width=11, fig.height=6, warning=FALSE}
# points 
ggplot(data=inv_projections, aes(x=reorder(inv_abbreviated, -hta_team_pts), y=hta_team_pts, fill=inv_abbreviated)) +
  geom_bar(stat="identity", width=0.6, colour="black") +
  geom_text(aes(label = hta_team_pts), size = 2.3, colour="black", fontface="bold", hjust = 0.5, vjust = 3) +
  theme_bw() +
  theme(axis.title.x=element_blank(), 
        axis.title.y=element_blank()) +
  labs(title = "The Invitational Rankings - Projected Team Points (Based on 2019 Hashtag Alt)", fill = "Team")

# rebounds 
ggplot(data=inv_projections, aes(x=reorder(inv_abbreviated, -hta_team_rebs), y=hta_team_rebs, fill=inv_abbreviated)) +
  geom_bar(stat="identity", width=0.6, colour="black") +
  geom_text(aes(label = hta_team_rebs), size = 2.3, colour="black", fontface="bold", hjust = 0.5, vjust = 3) +
  theme_bw() +
  theme(axis.title.x=element_blank(), 
        axis.title.y=element_blank()) +
  labs(title = "The Invitational Rankings - Projected Team Rebounds (Based on 2019 Hashtag Alt)", fill = "Team")

# assists 
ggplot(data=inv_projections, aes(x=reorder(inv_abbreviated, -hta_team_asts), y=hta_team_asts, fill=inv_abbreviated)) +
  geom_bar(stat="identity", width=0.6, colour="black") +
  geom_text(aes(label = hta_team_asts), size = 2.3, colour="black", fontface="bold", hjust = 0.5, vjust = 3) +
  theme_bw() +
  theme(axis.title.x=element_blank(), 
        axis.title.y=element_blank()) +
  labs(title = "The Invitational Rankings - Projected Team Assists (Based on 2019 Hashtag Alt)", fill = "Team")

# steals 
ggplot(data=inv_projections, aes(x=reorder(inv_abbreviated, -hta_team_stls), y=hta_team_stls, fill=inv_abbreviated)) +
  geom_bar(stat="identity", width=0.6, colour="black") +
  geom_text(aes(label = hta_team_stls), size = 2.3, colour="black", fontface="bold", hjust = 0.5, vjust = 3) +
  theme_bw() +
  theme(axis.title.x=element_blank(), 
        axis.title.y=element_blank()) +
  labs(title = "The Invitational Rankings - Projected Team Steals (Based on 2019 Hashtag Alt)", fill = "Team")

# blocks 
ggplot(data=inv_projections, aes(x=reorder(inv_abbreviated, -hta_team_blks), y=hta_team_blks, fill=inv_abbreviated)) +
  geom_bar(stat="identity", width=0.6, colour="black") +
  geom_text(aes(label = hta_team_blks), size = 2.3, colour="black", fontface="bold", hjust = 0.5, vjust = 3) +
  theme_bw() +
  theme(axis.title.x=element_blank(), 
        axis.title.y=element_blank()) +
  labs(title = "The Invitational Rankings - Projected Team Blocks (Based on 2019 Hashtag Alt)", fill = "Team")

# turnovers 
ggplot(data=inv_projections, aes(x=reorder(inv_abbreviated, hta_team_tovs), y=hta_team_tovs, fill=inv_abbreviated)) +
  geom_bar(stat="identity", width=0.6, colour="black") +
  geom_text(aes(label = hta_team_tovs), size = 2.3, colour="black", fontface="bold", hjust = 0.5, vjust = 3) +
  theme_bw() +
  theme(axis.title.x=element_blank(), 
        axis.title.y=element_blank()) +
  labs(title = "The Invitational Rankings - Projected Team Turnovers (Based on 2019 Hashtag Alt)", fill = "Team")

# threes 
ggplot(data=inv_projections, aes(x=reorder(inv_abbreviated, -hta_team_threes), y=hta_team_threes, fill=inv_abbreviated)) +
  geom_bar(stat="identity", width=0.6, colour="black") +
  geom_text(aes(label = hta_team_threes), size = 2.3, colour="black", fontface="bold", hjust = 0.5, vjust = 3) +
  theme_bw() +
  theme(axis.title.x=element_blank(), 
        axis.title.y=element_blank()) +
  labs(title = "The Invitational Rankings - Projected Team Threes (Based on 2019 Hashtag Alt)", fill = "Team")

# fgp 
ggplot(data=inv_projections, aes(x=reorder(inv_abbreviated, -hta_team_fgp), y=hta_team_fgp, fill=inv_abbreviated)) +
  geom_bar(stat="identity", width=0.6, colour="black") +
  geom_text(aes(label = round(hta_team_fgp,digits=2)), size = 2.3, colour="black", fontface="bold", hjust = 0.5, vjust = 3) +
  theme_bw() +
  theme(axis.title.x=element_blank(), 
        axis.title.y=element_blank()) +
  labs(title = "The Invitational Rankings - Projected Team FG% (Based on 2019 Hashtag Alt)", fill = "Team")

# ftp 
ggplot(data=inv_projections, aes(x=reorder(inv_abbreviated, -hta_team_ftp), y=hta_team_ftp, fill=inv_abbreviated)) +
  geom_bar(stat="identity", width=0.6, colour="black") +
  geom_text(aes(label = round(hta_team_ftp,digits=2)), size = 2.3, colour="black", fontface="bold", hjust = 0.5, vjust = 3) +
  theme_bw() +
  theme(axis.title.x=element_blank(), 
        axis.title.y=element_blank()) +
  labs(title = "The Invitational Rankings - Projected Team FG% (Based on 2019 Hashtag Alt)", fill = "Team")

```


```{r looking at specific team's player projections}
select_data %>% 
  filter(inv_abbreviated == "TREE") %>% 
  select(player, age, ht_pts:trade_comp) %>% 
  arrange(-ht_pts)
  
```








