---
title: "Franchise In-Season Tools"
author: "Brandon L. Kramer"
output: html_document
---

```{r setup, message=FALSE, warning=FALSE}

#install.packages("tidyverse"); install.packages("googlesheets")
rm(list = ls())
library("tidyverse")
library("plotly")
library("janitor")
source("../../funs/conv_to_points.R")
source("../../funs/trade_comp.R")
source("../../funs/adv_value_calc.R")

setwd("~/Documents/fantasy-basketball/data/nba_fantasy_data/")
bballref1920 <- read_csv("nba_fantasy_data - bballref1920.csv")
hashtag20 <- read_csv("nba_fantasy_data - 2020_hashtag_proj_clean.csv")
hashalt19 <- read_csv("nba_fantasy_data - 2019_hashtag_alt_proj.csv")
gsd2_inseason <- read_csv("Fantrax-Players-Gold Standard II.csv")
nba_schedule <- read_csv("nba_fantasy_data - 2019_nba_schedule.csv")
gsd2_contracts <- read_csv("nba_fantasy_data - gsd2_contracts_202021.csv") %>% 
  select(-position)
  
#gsd2_inseason <- gsd2_inseason %>% mutate(Trade = Status)

# 2018-19 projections from hashtag 
hashtag20 <- hashtag20 %>% 
  clean_nba_names(player) %>% 
  hashtag_avgs_to_fppg() %>% 
  select(player, contains("fppg"))

gsd2_contracts <- gsd2_contracts %>% 
  clean_nba_names(player)

# clean franchise data 
gsd2_inseason <- gsd2_inseason %>% 
  rename(fntx_pts = "PTS", fntx_orb = "OREB", fntx_dreb = "DREB", 
         fntx_ast = "AST", fntx_stl = "ST", fntx_blk = "BLK", 
         fntx_tov = "TO", fntx_threes = "3PTM", fntx_fga = "FG-", 
         fntx_ftm = "FTM", fntx_gms = "GP", fntx_fppg = "FP/G", fpts = FPts,
         trade_comp = "SAC_Trade", 
         nba_team = "Team", gsd2_team = "Status", player = "Player", position = "Position") %>%
  mutate(nba_team = recode(nba_team, PHO = "PHX", SA = "SAS", 
                           NY = "NYK", NO = "NOP", GS = "GSW")) %>% 
  clean_nba_names(player) 

# join all projections 
combined_data <- hashtag20 %>% 
  #full_join(hashtag20, by = "player") %>% 
  full_join(gsd2_contracts, by = "player") %>% 
  full_join(gsd2_inseason, by = "player") %>% 
  arrange(-gsd2_fppg_ht) %>% 
  select(player, gsd2_team, gsd2_fppg_ht, fpts, fntx_fppg, everything(), 
         -ld_fppg_ht, -botb_fppg_ht) 
 
select_data <- combined_data  

# Best FA available 
select_data; select_data %>% filter(gsd2_team == "FA")
```

# Glimpse at Overall Stats   

```{r looking at overall projections, message=FALSE, warning=FALSE}
select_data %>% 
  #filter(player == "Skal Labissiere") %>% # by player
  #filter(gsd2_team == "HOU") %>% 
  filter(trade_comp == "MEM") %>% 
  #filter(bbr_gms > 50) %>%        # by games played
  #filter(bbr_gsd2_fpts > 25) %>%    # by 2018 stats
  #filter(hta_gsd2_fpts > 25) %>%    # by hta projections 
  #filter(ht_gsd2_fpts > 25) %>%     # by ht projections 
  #filter(age < 25) %>%            # by age 
  #arrange(-bbr_gsd2_fpts) %>%       # arrange by 2018 stats
  #arrange(-hta_gsd2_fpts) %>%       # arrange by hta projections
  arrange(-fntx_fppg) %>%         # arrange by ht projections
  select(player, fntx_fppg, gsd2_fppg_ht, #gsd2_2020, gsd2_2021, gsd2_rfa, 
          )
```

#### Trade Comparison Tool 

```{r trade_comp_pre_ttls, fig.width=12, fig.height=4.5, message=FALSE, warning=FALSE}
source("../../funs/trade_comp.R")

pre_trade_fntx <- pre_trade_calc(df = select_data, league = "gsd2",
                                 current_team = gsd2_team, traded_to = trade_comp, 
                                 fppg_col = fntx_fppg, cap_col = gsd2_2020)
pre_trade_fntx; pre_trade_plot(pre_trade_fntx, var = "team_total", 
                               league = "gsd2", plotly = FALSE)
```
```{r trade_comp_post_ttls, fig.width=12, fig.height=4.5, message=FALSE, warning=FALSE}
post_trade_fntx <- post_trade_calc(df = select_data, league = "gsd2",
                                   current_team = gsd2_team, traded_to = trade_comp, 
                                   fppg_col = fntx_fppg, cap_col = gsd2_2020)
post_trade_fntx; post_trade_plot(post_trade_fntx, var = "team_total", 
                                 league = "gsd2", plotly = FALSE)
```
```{r trade_comp_pre_avgs, fig.width=12, fig.height=4.5, message=FALSE, warning=FALSE}
pre_trade_fntx <- pre_trade_calc(df = select_data, league = "gsd2",
                                 current_team = gsd2_team, traded_to = trade_comp, 
                                 fppg_col = fntx_fppg, cap_col = gsd2_2020)
pre_trade_fntx; pre_trade_plot(pre_trade_fntx, var = "avg_fppg", 
                               league = "gsd2", plotly = FALSE)
```
```{r trade_comp_post_avgs, fig.width=12, fig.height=4.5, message=FALSE, warning=FALSE}
post_trade_fntx <- post_trade_calc(df = select_data, league = "gsd2",
                                   current_team = gsd2_team, traded_to = trade_comp, 
                                   fppg_col = fntx_fppg, cap_col = gsd2_2020)
post_trade_fntx; post_trade_plot(post_trade_fntx, var = "avg_fppg", 
                                 league = "gsd2", plotly = FALSE)
```

#### Advanced Value Calculations 

##### Advanced Value By Player 

```{r, fig.width=10, fig.height=5, message=FALSE, warning=FALSE}
prediction_data <- adv_value_calc(select_data, 
                                  teams = "gsd2_team", 
                                  pts = "fntx_fppg",
                                  salaries = "gsd2_2020") %>% 
  rowid_to_column("rank"); prediction_data

# fntx residuals 
ggplot(prediction_data, aes(x = salaries, y = fppg)) +
  geom_smooth(method = "lm", se = FALSE, color = "black") +      
  geom_segment(aes(xend = salaries, yend = lm_pred), alpha = .2) +   
  geom_point(aes(color = abs(lm_value), size = abs(lm_value))) +  
  scale_color_continuous(low = "#ffcb0c", high = "#386890") +     
  guides(color = FALSE, size = FALSE) +                             
  geom_point(aes(y = lm_pred), shape = 1) +
  theme_minimal()
```

```{r, message=FALSE, warning=FALSE}
prediction_data %>% arrange(-salaries) %>% 
  select(rank, player, salaries, everything())
```

```{r, message=FALSE, warning=FALSE}
prediction_data %>% 
  filter(fppg > 20) %>% 
  mutate(cost_cats = if_else(salaries < 0.5, 1, 0),
         cost_cats = if_else(salaries > 5 & salaries < 10, 2, cost_cats),
         cost_cats = if_else(salaries > 10 & salaries < 15, 3, cost_cats),
         cost_cats = if_else(salaries > 15 & salaries < 20, 4, cost_cats),
         cost_cats = if_else(salaries > 20 & salaries < 25, 5, cost_cats),
         cost_cats = if_else(salaries > 25, 6, cost_cats)) %>% 
  group_by(cost_cats) %>% 
  summarize(value = sum(lm_norm)) %>% 
  mutate(cost_cats = recode(cost_cats,`0`="UFA",`1`="$<5M",
                            `2`="$5-$9.9M",`3`="$10-14.9M",
                            `4`="$15-19.9+M", `5`="$20-24.9+M", `6`="$25+M"))
```
##### Advanced Value By Team 

```{r, fig.width=10, message=FALSE, warning=FALSE}
value_by_teams <- team_value_structure(input_data = prediction_data,
                                         teams_col = teams, 
                                         value_col = lm_norm,
                                         fppg_col = fppg)
value_by_teams

value_by_players_graph <- value_by_teams %>% 
  #top_n(10, top10) %>% 
  #filter(teams %in% c("NOP", "MIN", "DET", "UTA", "PHX", "PHI")) %>% 
  pivot_longer(!teams, names_to = "players", values_to = "value_extracted") %>% 
  ggplot(aes(x=players, y=value_extracted, group=teams)) +
  geom_line(aes(color=teams))+
  scale_color_manual(values=franchise_team_colors) +
  theme() + theme_minimal(); ggplotly()
```

```{r, message=FALSE, warning=FALSE}
prediction_data %>% 
  filter(teams == "MEM")
```
```{r, message=FALSE, warning=FALSE}
prediction_data %>% 
  select(rank, player, teams, salaries, everything()) %>% 
  filter(teams == "MEM")
```

```{r, message=FALSE, warning=FALSE}
bad_teams <- c("LAL", "DAL", "SAS", "PHX", "ORL", "CHI",
               "OKC", "TOR", "BKN", "MIL", "PHI", "MEM",
               "GSW", "NOP", "CHA", "SAC", "LAC", "CHI")
  
prediction_data %>% 
  filter(teams %in% bad_teams & fppg > 20) %>% 
  select(rank, position, player, teams, salaries, everything()) %>% 
  left_join(select_data %>% select(player, starts_with("gsd2_20")), by = "player") %>% 
  filter(is.na(gsd2_2021) & grepl("PF|C", position)) # expiring contracts 
```

















