---
title: "Untitled"
author: "Brandon L. Kramer"
date: "10/28/2020"
output: html_document
---

```{r setup, include=FALSE, warning = FALSE}
rm(list = ls())
library(tidyverse)
library(janitor)
library(tidymodels)
source("~/Documents/fantasy-basketball/funs/conv_to_points.R")
setwd("~/Documents/fantasy-basketball/data/nba_player_data/nba_player_season/")
nba_data <- read_rds("nba_stats_19902019_dedup.Rds")
gsd2_data <- read_rds("gsd2_draft_data.Rds")
forthcoming_salaries <- read_csv("../nba_player_salaries/nba_salaries_201920.csv")

gsd2_data <- gsd2_data %>% 
  bbrhist_avgs_to_fppg() %>% 
  select(year, player, age, contains("fppg"), everything(), 
         -ld_fppg_bbr, -botb_fppg_bbr) %>%
  #filter(games > 5 & gsd2_fppg_bbr > 18) %>% 
  arrange(-gsd2_fppg_bbr) %>% 
  drop_na(salary, gsd2_fppg_bbr)
```

```{r}
ggplot(gsd2_data, aes(x = gsd2_fppg_bbr)) +
    geom_histogram(bins = 25) +
    labs(x = "Fantasy Points Per Game",
         y = "Number of Players") +
  theme_minimal()
```

```{r}
gsd2_data %>% summarise_all(~ sum(is.na(.)))
```

```{r}
gsd2_data <- gsd2_data %>% 
  mutate_if(is.character, as.factor) %>% 
  mutate(pos_pg = ifelse(str_detect(position, "\\b(?i)(PG)\\b"), "1", "0"),
         pos_sg = ifelse(str_detect(position, "\\b(?i)(SG)\\b"), "1", "0"),
         pos_sf = ifelse(str_detect(position, "\\b(?i)(SF)\\b"), "1", "0"),
         pos_pf = ifelse(str_detect(position, "\\b(?i)(PF)\\b"), "1", "0"),
         pos_c = ifelse(str_detect(position, "\\b(?i)(C)\\b"), "1", "0"),
         pos_pg = as.numeric(pos_pg),
         pos_sg = as.numeric(pos_sg),
         pos_sf = as.numeric(pos_sf),
         pos_pf = as.numeric(pos_pf),
         pos_c = as.numeric(pos_c)) %>% 
  select(year, age, games, per, ts_percent, orb_percent, drb_percent, ast_percent, vorp,
         stl_percent, blk_percent, tov_percent, usg_percent, fg_percent, ft_percent, x3p_percent, 
         pos_pg, pos_sg, pos_sf, pos_sf, pos_pf, pos_c, gsd2_fppg_bbr) %>% 
  filter(gsd2_fppg_bbr > 0) 

fit_all <- lm(gsd2_fppg_bbr ~ ., data = gsd2_data)
summary(fit_all)
```

```{r}
set.seed(1234)
gsd2_split <- gsd2_data %>%
    initial_split(prop = 0.8)

gsd2_train <- training(gsd2_split)
gsd2_test <- testing(gsd2_split)
```

```{r}
## a linear regression model specification
lm_mod <- linear_reg() %>%
    set_engine("lm")

lm_fit <- lm_mod %>%
    fit(log(gsd2_fppg_bbr) ~ ., data = gsd2_train)

lm_fit
```

```{r}
## a random forest model specification
rf_mod <- rand_forest() %>%
    set_mode("regression") %>%
    set_engine("randomForest")

fit_rf <- rf_mod %>%
    fit(log(gsd2_fppg_bbr) ~ ., data = gsd2_train)

fit_rf
```

```{r}
results <- gsd2_train %>%
    mutate(gsd2_fppg_bbr = log(gsd2_fppg_bbr)) %>%
    bind_cols(predict(lm_fit, gsd2_train) %>%
                  rename(.pred_lm = .pred)) %>%
    bind_cols(predict(fit_rf, gsd2_train) %>%
                  rename(.pred_rf = .pred))

# Evaluate the performance
metrics(results, truth = gsd2_fppg_bbr, estimate = .pred_lm)
metrics(results, truth = gsd2_fppg_bbr, estimate = .pred_rf)
```

```{r}
gsd2_boot <- bootstraps(gsd2_train)
```

```{r}
lm_res <- lm_mod %>%
    fit_resamples(
        log(gsd2_fppg_bbr) ~ .,
        resamples = gsd2_boot,
        control = control_resamples(save_pred = TRUE)
    )

rf_res <- rf_mod %>%
    fit_resamples(
        log(gsd2_fppg_bbr) ~ .,
        resamples = gsd2_boot,
        control = control_resamples(save_pred = TRUE)
    )

glimpse(rf_res)
```

```{r, fig.width=8, fig.height=4}
results <-  bind_rows(lm_res %>%
                          collect_predictions() %>%
                          mutate(model = "lm"),
                      rf_res %>%
                          collect_predictions() %>%
                          mutate(model = "rf"))
glimpse(results)

results %>%
    ggplot(aes(`log(gsd2_fppg_bbr)`, .pred)) +
    geom_abline(lty = 2, color = "gray50") +
    geom_point(aes(color = id), size = 1.5, alpha = 0.3, show.legend = FALSE) +
    geom_smooth(method = "lm") +
    facet_wrap(~ model) +
  theme_minimal()
```






```{r, fig.width=10, fig.height=5}
prediction_data <- gsd2_data %>% filter(games > 5 & gsd2_fppg_bbr > 18)
fit <- lm(gsd2_fppg_bbr ~ salary, data=prediction_data) # fit the model
prediction_data$predicted <- predict(fit)   # Save the predicted values
prediction_data$residuals <- residuals(fit) # Save the residual values

prediction_data <- arrange(prediction_data, desc(residuals)) %>%
  mutate(rank = 1:nrow(prediction_data)) %>% 
  select(rank, player, position, age, gsd2_fppg_bbr, residuals, games, everything()) %>% 
  mutate(player_label = ifelse(residuals > 10 & year > 2018, player, NA))

ggplot(prediction_data, aes(x = salary, y = gsd2_fppg_bbr)) +
  geom_smooth(method = "lm", se = FALSE, color = "black") +      
  geom_segment(aes(xend = salary, yend = predicted), alpha = .2) +   
  geom_point(aes(color = abs(residuals), size = abs(residuals))) + 
  geom_text(aes(label=player_label), size=3, hjust=0.5, vjust=0) +
  scale_color_continuous(low = "#386890", high = "#40E0D0") +     
  guides(color = FALSE, size = FALSE) +                             
  geom_point(aes(y = predicted), shape = 1) +
  scale_x_continuous(breaks = c(0, 5000000, 10000000, 15000000, 20000000, 25000000, 30000000, 35000000),
                     labels = c("0M", "5M", "10M", "15M", "20M", "25M", "30M", "35M")) +
  theme_minimal()
```
```{r}
prediction_data %>% 
  select(rank, player, position, age, gsd2_fppg_bbr, residuals, salary, year, everything()) %>% 
  filter(age < 22 & games > 5 & gsd2_fppg_bbr > 18)
```
```{r}
salaries <- forthcoming_salaries %>% 
  rename(player = Player) %>% 
  clean_nba_names() 

tmp_data <- prediction_data %>% 
  filter(year == 2019) %>% 
  select(player, gsd2_fppg_bbr, age, residuals, predicted, team)

tmp_data %>% 
  left_join(salaries, by = "player") %>% 
  select(-`Signed Using`, -Rk, -playerID, -Tm, -Guaranteed) %>% 
  mutate(`y2021-22` = replace_na(`y2021-22`, 0),
         `y2022-23` = replace_na(`y2022-23`, 0)) %>% 
  mutate(test20 = ifelse(`y2020-21` != 0, residuals, 0),
         test21 = ifelse(`y2021-22` != 0, residuals, 0),
         test22 = ifelse(`y2022-23` != 0, residuals, 0),
         test23 = ifelse(`y2023-24` != 0, residuals, 0)) %>%
  mutate(test_all = test20 + test21 + test22 + test23) %>% 
  select(player, test_all, everything()) %>% 
  arrange(-test_all)


```








```{r}
two_years <- prediction_data %>% filter(games > 5 & gsd2_fppg_bbr > 18)
mean(two_years$residuals)
position_count <- two_years %>% 
  mutate(position = str_replace_all(position, "PF-C", "PF"),
         position = str_replace_all(position, "SF-PF", "SF"),
         position = str_replace_all(position, "SF-SG", "SF"),
         position = str_replace_all(position, "PF-SF", "SF")) %>% 
  group_by(position) %>%
  count() %>% 
  rename(player_count = n) %>% 
  arrange(-player_count); position_count

two_years %>% 
  mutate(position = str_replace_all(position, "PF-C", "PF"),
         position = str_replace_all(position, "SF-PF", "SF"),
         position = str_replace_all(position, "SF-SG", "SF"),
         position = str_replace_all(position, "PF-SF", "SF")) %>%  
  group_by(position) %>%
  summarize(fppg_by_position = sum(gsd2_fppg_bbr)) %>% 
  left_join(position_count, by = "position") %>% 
  mutate(ffpg_normed = fppg_by_position / player_count) %>% 
  arrange(fppg_by_position)
```

*next steps* 
contract data for coming years 
projections for current nba players based on similar players???






















