---
title: "Franchise In-Season Tools"
author: "Brandon L. Kramer"
date: "11/26/2019"
output: html_document
---

```{r pull packages and projection data, include=FALSE}
#install.packages("tidyverse"); install.packages("googlesheets")
rm(list = ls())
for (pkg in c("googledrive", "googlesheets4", "tidyverse", "plotly")) {library(pkg, character.only = TRUE)}

setwd("C:/Users/bkram/CloudStation/NBA/data")
botb_contracts <- read_csv("nba_fantasy_data - botb_contracts.csv")
franchise_contracts <- read_csv("nba_fantasy_data - franchise_contracts.csv")
legacy_contracts <- read_csv("nba_fantasy_data - legacy_contracts.csv")
bballref18 <- read_csv("nba_fantasy_data - bballref18.csv")
hashalt19 <- read_csv("nba_fantasy_data - 2019_hashtag_alt_proj.csv")
hashtag19 <- read_csv("nba_fantasy_data - 2019_hashtag_proj.csv")
franchise_inseason <- read_csv("nba_fantasy_data - franchise_inseason.csv")
nba_schedule <- read_csv("nba_fantasy_data - 2019_nba_schedule.csv")

bballref18$player <- bballref18$player %>% 
  str_replace_all(c('Á' = 'A', 'ā' = 'a', 'á' = 'a', 'č' = 'c', 'ć' = 'c', 'è' = 'e', 
                    'é' = 'e', 'ê' = 'e', 'ić' = 'ic', 'ö' = 'o', 'ó' = 'o', 'Š' = 'S', 
                    'š' = 's', 'ū' = 'u', 'ý' = 'y', 'Ž' = 'Z', 'ž' = 'z', 'Élie' = 'Elie',
                    'P.J.' = 'PJ','C.J.' = 'CJ', 'R.J.' = 'RJ', 'T.J.' = 'TJ', 'D.J.' = 'DJ', 
                    'J.J.' = 'JJ', 'Dončić' = 'Doncic', "Demarre" = "DeMarre",
                    'Louis' = 'Lou', 'Edrice' = 'Bam', 'Waller-Prince' = 'Prince', "O.G." = "OG", 
                    'Jaren Jackson' = 'Jaren Jackson Jr.','Kelly Oubre' = 'Kelly Oubre Jr.', 
                    'Marvin Bagley' = 'Marvin Bagley III', 'Otto Porter' = 'Otto Porter Jr.', 
                    'Wendell Carter' = 'Wendell Carter Jr.', 'Larry Nance' = 'Larry Nance Jr.',
                    'Walt Lemon' = 'Walt Lemon Jr.', 'Dennis Schröder' = 'Dennis Schroder', 
                    'Tim Hardaway' = 'Tim Hardaway Jr.'))

combined_data <- bballref18 %>% 
  rename(bbr_pts = "PTS", bbr_dreb = "DRB", bbr_orb = "ORB",
         bbr_ast = "AST", bbr_stl = "STL", bbr_blk = "BLK",
         bbr_tov = "TOV", bbr_threes = "3P", bbr_fga = "FGA",
         bbr_fgm = "FG", bbr_ftm = "FT",  bbr_fta = "FTA", bbr_gms = "G", bbr_mpg = "MP", age = "Age") %>%
  mutate(bbr_ld_fpts = bbr_pts + (bbr_dreb*1.5) + (bbr_orb*2) + (bbr_ast*2) + (bbr_stl*2.5) + (bbr_blk*2.5) +
         (bbr_tov*-1) + bbr_threes + (bbr_fga*-0.5) + (bbr_fgm*0.5) + bbr_ftm + (bbr_fta*-1)) %>%
  mutate(bbr_fr_fpts = bbr_pts + (bbr_dreb*1.5) + (bbr_orb*2) + (bbr_ast*2) + (bbr_stl*2.5) + (bbr_blk*2.5) +
         (bbr_tov*-1) + bbr_threes + (bbr_fga*-0.5) + (bbr_fgm*0.5) + bbr_ftm + (bbr_fta*-1)) %>% 
  mutate(bbr_gsd2_fpts = bbr_pts + bbr_dreb + (bbr_orb*1.25) + (bbr_ast*1.5) + (bbr_stl*1.5) + (bbr_blk*2) +
         (bbr_tov*-1)+bbr_threes+(bbr_fga*-0.5)+(bbr_fgm*0.5)+(bbr_ftm*0.5)+(bbr_fta*-0.75)) %>%
  mutate(bbr_botb_fpts = bbr_pts + bbr_dreb + (bbr_orb*1.25) + (bbr_ast*1.5) + (bbr_stl*1.5) + (bbr_blk*2) +
         (bbr_tov*-1)+bbr_threes+(bbr_fga*-0.5)+(bbr_fgm*0.5)+(bbr_ftm*0.5)+(bbr_fta*-0.75)) %>% 
  select(player, age, bbr_ld_fpts, bbr_fr_fpts, bbr_gsd2_fpts, bbr_botb_fpts, bbr_gms, bbr_mpg,
         bbr_pts, bbr_dreb, bbr_orb, bbr_ast, bbr_stl, bbr_blk, bbr_tov, bbr_threes, bbr_fga, bbr_fgm, bbr_ftm, bbr_fta)

hashalt19$player <- hashalt19$player %>% 
  str_replace_all(c('Á' = 'A', 'ā' = 'a', 'á' = 'a', 'č' = 'c', 'ć' = 'c', 'è' = 'e', 'é' = 'e', 'ê' = 'e',
                    'ö' = 'o', 'ó' = 'o', 'Š' = 'S', 'š' = 's', 'ū' = 'u', 'ý' = 'y', 'Ž' = 'Z', 'ž' = 'z',
                    'P.J.' = 'PJ','C.J.' = 'CJ', 'R.J.' = 'RJ', 'T.J.' = 'TJ', 'D.J.' = 'DJ', 'J.J.' = 'JJ',
                    'Louis' = 'Lou', 'Edrice' = 'Bam', 'Waller-Prince' = 'Prince', "O.G." = "OG", 
                    'Jaren Jackson' = 'Jaren Jackson Jr.','Kelly Oubre' = 'Kelly Oubre Jr.', 
                    'Marvin Bagley' = 'Marvin Bagley III', 'Otto Porter' = 'Otto Porter Jr.', 
                    'Wendell Carter' = 'Wendell Carter Jr.', 'Larry Nance' = 'Larry Nance Jr.',
                    'Walt Lemon' = 'Walt Lemon Jr.', 'Dennis Schröder' = 'Dennis Schroder', 
                    'Tim Hardaway' = 'Tim Hardaway Jr.', "Demarre" = "DeMarre"))

hashalt19 <- hashalt19 %>% 
  rename(hta_pts = "PTS", hta_treb = "REB", hta_ast = "AST", hta_stl = "STL", hta_blk = "BLK",
         hta_tov = "TOV", hta_threes = "THREES", hta_fga = "FGA",hta_fgm = "FGM", hta_ftm = "FTM",  
         hta_fta = "FTA", hta_mpg = "MPG", hta_ftp = "FT", hta_gms = "Gs") %>%
  mutate(hta_dreb = hta_treb*0.78) %>% 
  mutate(hta_orb = hta_treb*0.22) %>% 
  mutate(hta_ld_fpts = hta_pts + (hta_dreb*1.5) + (hta_orb*2) + (hta_ast*2) + (hta_stl*2.5) + (hta_blk*2.5) +
         (hta_tov*-1) + hta_threes + (hta_fga*-0.5) + (hta_fgm*0.5) + hta_ftm + (hta_fta*-1)) %>%
  mutate(hta_fr_fpts = hta_pts + (hta_dreb*1.5) + (hta_orb*2) + (hta_ast*2) + (hta_stl*2.5) + (hta_blk*2.5) +
         (hta_tov*-1) + hta_threes + (hta_fga*-0.5) + (hta_fgm*0.5) + hta_ftm + (hta_fta*-1)) %>% 
  mutate(hta_gsd2_fpts = hta_pts + hta_dreb + (hta_orb*1.25) + (hta_ast*1.5) + (hta_stl*1.5) + (hta_blk*2) +
         (hta_tov*-1)+hta_threes+(hta_fga*-0.5)+(hta_fgm*0.5)+(hta_ftm*0.5)+(hta_fta*-0.75)) %>%
  mutate(hta_botb_fpts = hta_pts + hta_dreb + (hta_orb*1.25) + (hta_ast*1.5) + (hta_stl*1.5) + (hta_blk*2) +
         (hta_tov*-1)+hta_threes+(hta_fga*-0.5)+(hta_fgm*0.5)+(hta_ftm*0.5)+(hta_fta*-0.75)) %>% 
  select(player, hta_ld_fpts, hta_fr_fpts, hta_gsd2_fpts, hta_botb_fpts, hta_gms, hta_mpg, 
         hta_pts, hta_dreb, hta_orb, hta_ast, hta_stl, hta_blk, hta_tov, hta_threes, hta_fga, hta_fgm, hta_ftm, hta_fta, hta_ftp)
  
combined_data <- combined_data %>% 
  full_join(hashalt19, by = "player")

hashtag19$player <- hashtag19$player %>% 
  str_replace_all(c('Á' = 'A', 'ā' = 'a', 'á' = 'a', 'č' = 'c', 'ć' = 'c', 'è' = 'e', 'é' = 'e', 'ê' = 'e',
                    'ö' = 'o', 'ó' = 'o', 'Š' = 'S', 'š' = 's', 'ū' = 'u', 'ý' = 'y', 'Ž' = 'Z', 'ž' = 'z',
                    'P.J.' = 'PJ','C.J.' = 'CJ', 'R.J.' = 'RJ', 'T.J.' = 'TJ', 'D.J.' = 'DJ', 'J.J.' = 'JJ',
                    'Louis' = 'Lou', 'Edrice' = 'Bam', 'Waller-Prince' = 'Prince', "O.G." = "OG", 
                    "Demarre" = "DeMarre", 'Dennis Schröder' = 'Dennis Schroder'))

hashtag19 <- hashtag19 %>% 
  rename(ht_pts = "PTS", ht_dreb = "DREB", ht_orb = "OREB", ht_ast = "AST", ht_stl = "STL", ht_blk = "BLK",
         ht_tov = "TO", ht_threes = "THREES", ht_fga = "FGA", ht_fgm = "FGM", ht_ftm = "FTM",  
         ht_fta = "FTA", ht_mpg = "MPG", ht_gms = "GP", ht_fgp = "FG%", ht_ftp = "FT%") %>%
  mutate(ht_ld_fpts = ht_pts + (ht_dreb*1.5) + (ht_orb*2) + (ht_ast*2) + (ht_stl*2.5) + (ht_blk*2.5) +
         (ht_tov*-1) + ht_threes + (ht_fga*-0.5) + (ht_fgm*0.5) + ht_ftm + (ht_fta*-1)) %>%
  mutate(ht_fr_fpts = ht_pts + (ht_dreb*1.5) + (ht_orb*2) + (ht_ast*2) + (ht_stl*2.5) + (ht_blk*2.5) +
         (ht_tov*-1) + ht_threes + (ht_fga*-0.5) + (ht_fgm*0.5) + ht_ftm + (ht_fta*-1)) %>% 
  mutate(ht_gsd2_fpts = ht_pts + ht_dreb + (ht_orb*1.25) + (ht_ast*1.5) + (ht_stl*1.5) + (ht_blk*2) +
         (ht_tov*-1)+ht_threes+(ht_fga*-0.5)+(ht_fgm*0.5)+(ht_ftm*0.5)+(ht_fta*-0.75)) %>%
  mutate(ht_botb_fpts = ht_pts + ht_dreb + (ht_orb*1.25) + (ht_ast*1.5) + (ht_stl*1.5) + (ht_blk*2) +
         (ht_tov*-1)+ht_threes+(ht_fga*-0.5)+(ht_fgm*0.5)+(ht_ftm*0.5)+(ht_fta*-0.75)) %>% 
  select(player, ht_ld_fpts, ht_fr_fpts, ht_gsd2_fpts, ht_botb_fpts, ht_gms, ht_mpg, 
         ht_pts, ht_dreb, ht_orb, ht_ast, ht_stl, ht_blk, ht_tov, ht_threes, ht_fga, ht_fgm, ht_fgp, ht_ftm, ht_fta, ht_ftp)

combined_data <- combined_data %>% 
  full_join(hashtag19, by = "player")

franchise_contracts$player <- franchise_contracts$player %>% 
  str_replace_all(c('C.J.' = 'CJ', 'R.J.' = 'RJ', 'T.J.' = 'TJ', 'D.J.' = 'DJ', "O.G." = "OG", 
                    'Louis' = 'Lou', 'Edrice' = 'Bam', 'Waller-Prince' = 'Prince', "Demarre" = "DeMarre",
                    'Á' = 'A', 'ā' = 'a', 'á' = 'a', 'č' = 'c', 'ć' = 'c', 'è' = 'e', 'é' = 'e', 'ê' = 'e',
                    'ö' = 'o', 'ó' = 'o', 'Š' = 'S', 'š' = 's', 'ū' = 'u', 'ý' = 'y', 'Ž' = 'Z', 'ž' = 'z',
                    'P.J.' = 'PJ','C.J.' = 'CJ', 'R.J.' = 'RJ', 'T.J' = 'TJ', 'D.J.' = 'DJ', 'J.J.' = 'JJ'))

combined_data <- combined_data %>% 
  full_join(franchise_contracts, by = "player") %>% select(-fr_team, -trade_comp)

# in-season fantrax 

franchise_inseason$player <- franchise_inseason$Player %>% 
  str_replace_all(c('Á' = 'A', 'ā' = 'a', 'á' = 'a', 'č' = 'c', 'ć' = 'c', 'è' = 'e', 'é' = 'e', 'ê' = 'e',
                    'ö' = 'o', 'ó' = 'o', 'Š' = 'S', 'š' = 's', 'ū' = 'u', 'ý' = 'y', 'Ž' = 'Z', 'ž' = 'z',
                    'P.J.' = 'PJ','C.J.' = 'CJ', 'R.J.' = 'RJ', 'T.J.' = 'TJ', 'D.J.' = 'DJ', 'J.J.' = 'JJ',
                    'Louis' = 'Lou', 'Edrice' = 'Bam', 'Waller-Prince' = 'Prince', "O.G." = "OG", 
                    'Walt Lemon' = 'Walt Lemon Jr.', 'Dennis Schröder' = 'Dennis Schroder', "Demarre" = "DeMarre"))

franchise_inseason <- franchise_inseason %>% 
  rename(fntx_pts = "PTS", fntx_orb = "OREB", fntx_dreb = "DREB", fntx_ast = "AST", fntx_stl = "ST", 
         fntx_blk = "BLK", fntx_tov = "TO", fntx_threes = "3PTM", fntx_fga = "FGA",fntx_fgm = "FGM", 
         trade_comp = "Trade",
         fntx_ftm = "FTM", fntx_fta = "FTA", fntx_gms = "GP", fntx_fppg = "FP/G", fr_team = "Status") %>%
  mutate(fntx_ld_fpts = fntx_pts + (fntx_dreb*1.5) + (fntx_orb*2) + (fntx_ast*2) + (fntx_stl*2.5) + (fntx_blk*2.5) +
         (fntx_tov*-1) + fntx_threes + (fntx_fga*-0.5) + (fntx_fgm*0.5) + fntx_ftm + (fntx_fta*-1)) %>%
  mutate(fntx_fr_fpts = fntx_pts + (fntx_dreb*1.5) + (fntx_orb*2) + (fntx_ast*2) + (fntx_stl*2.5) + (fntx_blk*2.5) +
         (fntx_tov*-1) + fntx_threes + (fntx_fga*-0.5) + (fntx_fgm*0.5) + fntx_ftm + (fntx_fta*-1)) %>% 
  mutate(fntx_gsd2_fpts = fntx_pts + fntx_dreb + (fntx_orb*1.25) + (fntx_ast*1.5) + (fntx_stl*1.5) + (fntx_blk*2) +
         (fntx_tov*-1)+fntx_threes+(fntx_fga*-0.5)+(fntx_fgm*0.5)+(fntx_ftm*0.5)+(fntx_fta*-0.75)) %>%
  mutate(fntx_botb_fpts = fntx_pts + fntx_dreb + (fntx_orb*1.25) + (fntx_ast*1.5) + (fntx_stl*1.5) + (fntx_blk*2) +
         (fntx_tov*-1)+fntx_threes+(fntx_fga*-0.5)+(fntx_fgm*0.5)+(fntx_ftm*0.5)+(fntx_fta*-0.75)) %>% 
  rename(nba_team = "Team") %>% 
  mutate(nba_team = recode(nba_team, PHO = "PHX", SA = "SAS", NY = "NYK", NO = "NOP", GS = "GSW")) %>% 
  select(player, fntx_fppg, fntx_ld_fpts, fntx_fr_fpts, fntx_gsd2_fpts, fntx_botb_fpts, fntx_gms,  
         fntx_pts, fntx_dreb, fntx_orb, fntx_ast, fntx_stl, fntx_blk, 
         trade_comp, 
         fntx_tov, fntx_threes, fntx_fga, fntx_fgm, fntx_ftm, fntx_fta, fr_team, nba_team)

select_data <- combined_data %>% 
  inner_join(franchise_inseason, by = "player") %>% 
  select(player, age, fntx_fppg, bbr_fr_fpts, hta_fr_fpts, ht_fr_fpts, 
         bbr_gms, bbr_mpg, hta_gms, hta_mpg, ht_gms, ht_mpg,
         fr_team, fr_2019, fr_2020, fr_2021, fr_2022, fr_2023, fr_2024, 
         trade_comp, 
         fr_rfa, fr_injured, fr_gleague, fr_intl, fr_position, nba_team) %>%   
  inner_join(nba_schedule, by = "nba_team") %>%  
  mutate(playoff1 = week20,playoff2 = week21,playoff3 = week22,playoff4 = week23) %>% 
  # regular season schedule 
  mutate(week1_totals = (fntx_fppg * week1)) %>%
  mutate(week2_totals = (fntx_fppg * week2)) %>%
  mutate(week3_totals = (fntx_fppg * week3)) %>%
  mutate(week4_totals = (fntx_fppg * week4)) %>%
  mutate(week5_totals = (fntx_fppg * week5)) %>%
  mutate(week6_totals = (fntx_fppg * week6)) %>%
  mutate(week7_totals = (fntx_fppg * week7)) %>%
  mutate(week8_totals = (fntx_fppg * week8)) %>%
  mutate(week9_totals = (fntx_fppg * week9)) %>% 
  mutate(week10_totals = (fntx_fppg * week10)) %>%  
  mutate(week11_totals = (fntx_fppg * week11)) %>%
  mutate(week12_totals = (fntx_fppg * week12)) %>%
  mutate(week13_totals = (fntx_fppg * week13)) %>%
  mutate(week14_totals = (fntx_fppg * week14)) %>%
  mutate(week15_totals = (fntx_fppg * week15)) %>%
  mutate(week16_totals = (fntx_fppg * week16)) %>%
  mutate(week17_totals = (fntx_fppg * week17)) %>%
  mutate(week18_totals = (fntx_fppg * week18)) %>%
  mutate(week19_totals = (fntx_fppg * week19)) %>%
  # playoff totals 
  mutate(playoff1_totals = (fntx_fppg * playoff1)) %>%
  mutate(playoff2_totals = (fntx_fppg * playoff2)) %>%
  mutate(playoff3_totals = (fntx_fppg * playoff3)) %>%
  mutate(playoff4_totals = (fntx_fppg * playoff4)) %>% 
  filter(player != "Rodions Kurucs" & player != "Jontay Porter" & player != "Chimezie Metu" & player != "Issuf Sanon" &
         player != "Dewan Hernandez" & player != "Ognen Jaramaz" & player != "Marial Shayok" & player != "Justin James" &
         player != "Didi Louzada Silva" &  player != "Alessandro Gentile" ) 
  
rm(bballref18, hashtag19, hashalt19, franchise_contracts)
```

# Glimpse at Overall Stats   

```{r looking at overall projections}
select_data %>% 
  #filter(player == "Skal Labissiere") %>% # by player
  filter(fr_team == "BOS") %>% 
  #filter(bbr_gms > 50) %>%        # by games played
  #filter(bbr_fr_fpts > 25) %>%    # by 2018 stats
  #filter(hta_fr_fpts > 25) %>%    # by hta projections 
  #filter(ht_fr_fpts > 25) %>%     # by ht projections 
  #filter(age < 25) %>%            # by age 
  #arrange(-bbr_fr_fpts) %>%       # arrange by 2018 stats
  #arrange(-hta_fr_fpts) %>%       # arrange by hta projections
  arrange(-fntx_fppg) %>%         # arrange by ht projections
  select(player, age, fntx_fppg, fr_2019, fr_2020, fr_2021, fr_rfa, 
         bbr_fr_fpts, hta_fr_fpts, ht_fr_fpts, fr_injured, fr_gleague, fr_intl)
```

# Value Calculators 

```{r hashtag evaluations in fr}
select_data %>% 
  mutate(fntx_value_19 = fntx_fppg / fr_2019 * 10000) %>% 
  mutate(fntx_value_20 = fntx_fppg / fr_2020 * 10000) %>%
  mutate(fntx_value_21 = fntx_fppg / fr_2021 * 10000) %>%
  mutate(diff = fntx_fppg - ht_fr_fpts) %>%
  filter(fntx_fppg > 28) %>% 
  filter(fr_team == "MIA" | fr_team == "UTA" | fr_team == "DAL" | fr_team == "LAC" |  
         fr_team == "MEM" | fr_team == "WAS" | fr_team == "BKN" | fr_team == "MIL" | 
         fr_team == "DET" | fr_team == "IND" | fr_team == "ORL" 
         # | fr_team == "NOP" | fr_team == "CHI"  
        ) %>%
  #filter(fr_team == "CLE") %>% 
  #filter(age < 25) %>% 
  arrange(-fntx_value_19) %>% 
  select(player, age, fr_team, fntx_fppg, ht_fr_fpts, diff, fntx_value_19, fntx_value_20, 
         fr_2019, fr_2020, fr_2021, fr_rfa, fr_injured, fr_gleague, fr_intl)
```

```{r playoff-value-calculator}
# playoff value with schedule accounted for 
select_data %>% 
  mutate(totals_playoff1 = (fntx_fppg * playoff1)) %>% 
  mutate(totals_playoff2 = (fntx_fppg * playoff2)) %>%
  mutate(totals_playoff3 = (fntx_fppg * playoff3)) %>%
  mutate(totals_playoff4 = (fntx_fppg * playoff4)) %>%
  mutate(sum_playoff_total = totals_playoff1+totals_playoff2+totals_playoff3+totals_playoff4) %>% 
  mutate(playoff_value = (sum_playoff_total / fr_2019)) %>% 
  select(player, fntx_fppg, playoff_value, sum_playoff_total,
         totals_playoff1,totals_playoff2,totals_playoff3,totals_playoff4, everything()) %>% 
  filter(fntx_fppg > 30) %>% arrange(-playoff_value)
```

```{r per-week-scores, fig.width=12, fig.height=10, warning=FALSE}

# regular season 
week1_totals <- select_data %>% group_by(fr_team) %>% top_n(n = 15, wt = fntx_fppg) %>% summarise(week1_totals = sum(week1_totals)) 
week2_totals <- select_data %>% group_by(fr_team) %>% top_n(n = 15, wt = fntx_fppg) %>% summarise(week2_totals = sum(week2_totals)) 
week3_totals <- select_data %>% group_by(fr_team) %>% top_n(n = 15, wt = fntx_fppg) %>% summarise(week3_totals = sum(week3_totals)) 
week4_totals <- select_data %>% group_by(fr_team) %>% top_n(n = 15, wt = fntx_fppg) %>% summarise(week4_totals = sum(week4_totals)) 
week5_totals <- select_data %>% group_by(fr_team) %>% top_n(n = 15, wt = fntx_fppg) %>% summarise(week5_totals = sum(week5_totals)) 
week6_totals <- select_data %>% group_by(fr_team) %>% top_n(n = 15, wt = fntx_fppg) %>% summarise(week6_totals = sum(week6_totals)) 
week7_totals <- select_data %>% group_by(fr_team) %>% top_n(n = 15, wt = fntx_fppg) %>% summarise(week7_totals = sum(week7_totals)) 
week8_totals <- select_data %>% group_by(fr_team) %>% top_n(n = 15, wt = fntx_fppg) %>% summarise(week8_totals = sum(week8_totals)) 
week9_totals <- select_data %>% group_by(fr_team) %>% top_n(n = 15, wt = fntx_fppg) %>% summarise(week9_totals = sum(week9_totals))
week10_totals <- select_data %>% group_by(fr_team) %>% top_n(n = 15, wt = fntx_fppg) %>% summarise(week10totals = sum(week10_totals))
week11_totals <- select_data %>% group_by(fr_team) %>% top_n(n = 15, wt = fntx_fppg) %>% summarise(week11_totals = sum(week11_totals)) 
week12_totals <- select_data %>% group_by(fr_team) %>% top_n(n = 15, wt = fntx_fppg) %>% summarise(week12_totals = sum(week12_totals)) 
week13_totals <- select_data %>% group_by(fr_team) %>% top_n(n = 15, wt = fntx_fppg) %>% summarise(week13_totals = sum(week13_totals)) 
week14_totals <- select_data %>% group_by(fr_team) %>% top_n(n = 15, wt = fntx_fppg) %>% summarise(week14_totals = sum(week14_totals)) 
week15_totals <- select_data %>% group_by(fr_team) %>% top_n(n = 15, wt = fntx_fppg) %>% summarise(week15_totals = sum(week15_totals)) 
week16_totals <- select_data %>% group_by(fr_team) %>% top_n(n = 15, wt = fntx_fppg) %>% summarise(week16_totals = sum(week16_totals)) 
week17_totals <- select_data %>% group_by(fr_team) %>% top_n(n = 15, wt = fntx_fppg) %>% summarise(week17_totals = sum(week17_totals)) 
week18_totals <- select_data %>% group_by(fr_team) %>% top_n(n = 15, wt = fntx_fppg) %>% summarise(week18_totals = sum(week18_totals)) 
week19_totals <- select_data %>% group_by(fr_team) %>% top_n(n = 15, wt = fntx_fppg) %>% summarise(week19_totals = sum(week19_totals))

# playoff totals by team 
playoff1_totals <- select_data %>% group_by(fr_team) %>% summarise(playoff1_totals = sum(playoff1_totals))
playoff2_totals <- select_data %>% group_by(fr_team) %>% summarise(playoff2_totals = sum(playoff2_totals))
playoff3_totals <- select_data %>% group_by(fr_team) %>% summarise(playoff3_totals = sum(playoff3_totals))
playoff4_totals <- select_data %>% group_by(fr_team) %>% summarise(playoff4_totals = sum(playoff4_totals))

weekly_totals <- right_join(week1_totals,week2_totals, by = "fr_team") %>% 
  right_join(week3_totals, by = "fr_team") %>% 
  right_join(week4_totals, by = "fr_team") %>% 
  right_join(week5_totals, by = "fr_team") %>% 
  right_join(week6_totals, by = "fr_team") %>% 
  right_join(week7_totals, by = "fr_team") %>% 
  right_join(week8_totals, by = "fr_team") %>% 
  right_join(week9_totals, by = "fr_team") %>%
  right_join(week10_totals, by = "fr_team") %>%
  right_join(week11_totals, by = "fr_team") %>%
  right_join(week12_totals, by = "fr_team") %>% 
  right_join(week13_totals, by = "fr_team") %>% 
  right_join(week14_totals, by = "fr_team") %>% 
  right_join(week15_totals, by = "fr_team") %>% 
  right_join(week16_totals, by = "fr_team") %>% 
  right_join(week17_totals, by = "fr_team") %>% 
  right_join(week18_totals, by = "fr_team") %>% 
  right_join(week19_totals, by = "fr_team") %>% 
  right_join(playoff1_totals, by = "fr_team") %>% 
  right_join(playoff2_totals, by = "fr_team") %>% 
  right_join(playoff3_totals, by = "fr_team") %>% 
  right_join(playoff4_totals, by = "fr_team")  

rm(week1_totals,week2_totals,week3_totals,week4_totals,
   week5_totals,week6_totals,week7_totals,week8_totals,week9_totals,
  week10_totals,week11_totals,week12_totals,week13_totals,week14_totals,
   week15_totals,week16_totals,week17_totals,week18_totals,week19_totals,
   playoff1_totals,playoff2_totals,playoff3_totals,playoff4_totals)


weekly_totals <- as_tibble(t(weekly_totals)) 
colnames(weekly_totals) <- as.matrix(weekly_totals[1,])
weekly_totals <- weekly_totals[-1,]
week <- as_tibble(c("1","2","3","4","5","6","7","8","9",
                    "10", "11", "12", "13", "14", "15", 
                    "16", "17", "18", "19", "20", "21", "22", "23"))
weekly_totals <- weekly_totals %>% bind_cols(week) %>% rename(week = "value")
weekly_totals <- as_tibble(sapply(weekly_totals, as.numeric ))
weekly_totals <- weekly_totals %>% select(week, everything()); rm(week)
class(weekly_totals)

weekly_totals_plot <- weekly_totals %>% 
  filter(week > 9 & week < 20) %>% # games that have passed in regular season 
  #filter(week > 19 & week < 24) %>% # playoff filter 
  ggplot() +
  geom_line(aes(y = ATL, x = week, colour = "ATL"), group = 1) +
  geom_line(aes(y = BKN, x = week, colour = "BKN"), group = 1) +
  geom_line(aes(y = BOS, x = week, colour = "BOS"), group = 1) +
  geom_line(aes(y = CHA, x = week, colour = "CHA"), group = 1) +
  geom_line(aes(y = CHI, x = week, colour = "CHI"), group = 1, size = 1.2) + # pick 
  geom_line(aes(y = CLE, x = week, colour = "CLE"), group = 1, size = 1.2) + # pick 
  geom_line(aes(y = DAL, x = week, colour = "DAL"), group = 1) +
  geom_line(aes(y = DEN, x = week, colour = "DEN"), group = 1) +
  geom_line(aes(y = DET, x = week, colour = "DET"), group = 1) +
  geom_line(aes(y = GSW, x = week, colour = "GSW"), group = 1) +
  geom_line(aes(y = HOU, x = week, colour = "HOU"), group = 1) +
  geom_line(aes(y = IND, x = week, colour = "IND"), group = 1, size = 1.2) + # pick 
  geom_line(aes(y = LAC, x = week, colour = "LAC"), group = 1) +
  geom_line(aes(y = LAL, x = week, colour = "LAL"), group = 1) +
  geom_line(aes(y = MEM, x = week, colour = "MEM"), group = 1) +
  geom_line(aes(y = MIA, x = week, colour = "MIA"), group = 1) +
  geom_line(aes(y = MIL, x = week, colour = "MIL"), group = 1) +
  geom_line(aes(y = MIN, x = week, colour = "MIN"), group = 1) +
  geom_line(aes(y = NOP, x = week, colour = "NOP"), group = 1, size = 1.2) + # pick 
  geom_line(aes(y = NYK, x = week, colour = "NYK"), group = 1) +
  geom_line(aes(y = OKC, x = week, colour = "OKC"), group = 1) +
  geom_line(aes(y = ORL, x = week, colour = "ORL"), group = 1, size = 1.2) + # pick 
  geom_line(aes(y = PHI, x = week, colour = "PHI"), group = 1) +
  geom_line(aes(y = PHX, x = week, colour = "PHX"), group = 1) +
  geom_line(aes(y = POR, x = week, colour = "POR"), group = 1) +
  geom_line(aes(y = SAC, x = week, colour = "SAC"), group = 1) + 
  geom_line(aes(y = SAS, x = week, colour = "SAS"), group = 1) +
  geom_line(aes(y = TOR, x = week, colour = "TOR"), group = 1) +
  geom_line(aes(y = UTA, x = week, colour = "UTA"), group = 1) +
  geom_line(aes(y = WAS, x = week, colour = "WAS"), group = 1, size = 1.2) + # pick 
  labs(title = "Projected Weekly Totals in Franchise") + 
  scale_color_manual(values=c("#C8102E", "#061922", "#008348", "#00788C", "#ce1141", 
                             "#860038", "#007dc5", "#0E2240", "#C8102E", "#1D428A",
                             "#ce1141", "#ffc633", "#1D428A", "#552582", "#5D76A9", 
                             "#98002e", "#00471b", "#78be20", "#b6995a", "#F58426",
                             "#EF3B24", "#007dc5", "#006bb6", "#e56020", "#000000", 
                             "#724c9f", "#bac3c9", "#ce1141", "#002B5C", "#002b5c")) +
  #scale_x_discrete(breaks=seq()) +
  theme(axis.title.x = element_blank(), axis.ticks.x = element_blank(),
        axis.title.y = element_blank(), legend.title = element_blank()); ggplotly()
```

WAS:
ORL:
IND: 
NOP:
CHI:
CLE: 

# Trade Tool with Fantrax Data 

```{r comparing team projections before and after trade using ht, fig.width=12, fig.height=4.5, warning=FALSE}
temp_1 <- select_data %>% 
  #filter(fr_injured == "0") %>% 
  #filter(fr_gleague == "0") %>% 
  #filter(fr_intl == "0") %>%  
  filter(fr_team != "FA") %>% drop_na(fr_team) %>%
  group_by(fr_team) %>% top_n(15, wt = fntx_fppg) %>% summarize(avg_fppg = mean(fntx_fppg, na.rm = TRUE)) 
temp_2 <- select_data %>% 
  #filter(fr_injured == "0") %>% 
  #filter(fr_gleague == "0") %>% 
  #filter(fr_intl == "0") %>% 
  filter(fr_team != "FA") %>% drop_na(fr_team) %>%
  group_by(fr_team) %>% top_n(15, wt = fntx_fppg) %>% summarize(fr_players = n()) %>% filter(fr_team != "NA") %>% 
  full_join(temp_1, temp_2, by = "fr_team")
temp_3 <- select_data %>% 
  #filter(fr_injured == "0") %>% 
  #filter(fr_gleague == "0") %>% 
  #filter(fr_intl == "0") %>% 
  filter(fr_team != "FA") %>% drop_na(fr_team) %>%
  group_by(fr_team) %>% top_n(15, wt = fntx_fppg) %>% 
  summarize(cap_used = sum(fr_2019, na.rm = TRUE)) %>% 
  mutate(cap_left = 109400000 - cap_used)
pre_trade <- full_join(temp_2, temp_3, by = "fr_team") %>% 
  mutate(team_total = avg_fppg * fr_players) %>% 
  arrange(-team_total) %>%
  select(fr_team, fr_players, avg_fppg, team_total, cap_used, cap_left); rm(temp_1, temp_2); rm(temp_3)

temp_1 <- select_data %>% 
  #filter(fr_injured == "0") %>% 
  #filter(fr_gleague == "0") %>% 
  #filter(fr_intl == "0") %>%  
  filter(fr_team != "FA") %>% drop_na(fr_team) %>%
  group_by(trade_comp) %>% top_n(15, wt = fntx_fppg) %>% summarize(avg_fppg = mean(fntx_fppg, na.rm = TRUE)) 
temp_2 <- select_data %>% 
  #filter(fr_injured == "0") %>% 
  #filter(fr_gleague == "0") %>% 
  #filter(fr_intl == "0") %>% 
  filter(fr_team != "FA") %>% drop_na(fr_team) %>%
  group_by(trade_comp) %>% top_n(15, wt = fntx_fppg) %>% summarize(fr_players = n()) %>% filter(trade_comp != "NA") %>% 
  full_join(temp_1, temp_2, by = "trade_comp")
temp_3 <- select_data %>% 
  #filter(fr_injured == "0") %>% 
 # filter(fr_gleague == "0") %>% 
  #filter(fr_intl == "0") %>% 
  filter(fr_team != "FA") %>% drop_na(fr_team) %>%
  group_by(trade_comp) %>% top_n(15, wt = fntx_fppg) %>% 
  summarize(cap_used = sum(fr_2019, na.rm = TRUE)) %>% 
  mutate(cap_left = 109400000 - cap_used)
post_trade <- full_join(temp_2, temp_3, by = "trade_comp") %>% 
  mutate(team_total = avg_fppg * fr_players) %>% 
  arrange(-team_total) %>%
  select(trade_comp, fr_players, avg_fppg, team_total, cap_used, cap_left); rm(temp_1, temp_2); rm(temp_3)

ggplot(data=pre_trade, 
       aes(x=reorder(fr_team, -team_total), y=team_total, fill=fr_team)) +
  geom_bar(stat="identity", width=0.6, colour="black") +
  theme_bw() +  theme(axis.title.x=element_blank(), axis.title.y=element_blank()) +
  geom_text(aes(label = fr_players), size = 3, colour="white", fontface="bold", hjust = 0.5, vjust = 5) +
  labs(title = "Franchise NBA Rankings - Projected Team Points Per Week (HT 2019 Stats - Before)", 
       fill = "Franchise Team") +
  scale_fill_manual(values=c("#C8102E", "#061922", "#008348", "#00788C", "#ce1141", 
                             "#860038", "#007dc5", "#0E2240", "#C8102E", "#1D428A",
                             "#ce1141", "#ffc633", "#1D428A", "#552582", "#5D76A9", 
                             "#98002e", "#00471b", "#78be20", "#b6995a", "#F58426",
                             "#EF3B24", "#007dc5", "#006bb6", "#e56020", "#000000", 
                             "#724c9f", "#bac3c9", "#ce1141", "#002B5C", "#002b5c")); ggplotly() 

ggplot(data=post_trade, 
       aes(x=reorder(trade_comp, -team_total), y=team_total, fill=trade_comp)) +
  geom_bar(stat="identity", width=0.6, colour="black") +
  theme_bw() +  theme(axis.title.x=element_blank(), axis.title.y=element_blank()) +
  geom_text(aes(label = fr_players), size = 3, colour="white", fontface="bold", hjust = 0.5, vjust = 5) +
  labs(title = "Franchise NBA Rankings - Projected Team Points Per Week (HT 2019 Stats - After)", 
       fill = "Franchise Team") +
  scale_fill_manual(values=c("#C8102E", "#061922", "#008348", "#00788C", "#ce1141", 
                             "#860038", "#007dc5", "#0E2240", "#C8102E", "#1D428A",
                             "#ce1141", "#ffc633", "#1D428A", "#552582", "#5D76A9", 
                             "#98002e", "#00471b", "#78be20", "#b6995a", "#F58426",
                             "#EF3B24", "#007dc5", "#006bb6", "#e56020", "#000000", 
                             "#724c9f", "#bac3c9", "#ce1141", "#002B5C", "#002b5c")); ggplotly()

ggplot(data=pre_trade, aes(x=reorder(fr_team, -avg_fppg), y=avg_fppg, fill=fr_team)) +
  geom_bar(stat="identity", width=0.6, colour="black") +
  theme_bw() + theme(axis.title.x=element_blank(), axis.title.y=element_blank()) +
  geom_text(aes(label = fr_players), size = 3, colour="white", fontface="bold", hjust = 0.5, vjust = 3) +
  labs(title = "Franchise NBA Rankings - Avg Fantasy Points Per Player (HT 2019 Stats - Before)", 
       fill = "Franchise Team") +
  scale_fill_manual(values=c("#C8102E", "#061922", "#008348", "#00788C", "#ce1141", 
                             "#860038", "#007dc5", "#0E2240", "#C8102E", "#1D428A",
                             "#ce1141", "#ffc633", "#1D428A", "#552582", "#5D76A9", 
                             "#98002e", "#00471b", "#78be20", "#b6995a", "#F58426",
                             "#EF3B24", "#007dc5", "#006bb6", "#e56020", "#000000", 
                             "#724c9f", "#bac3c9", "#ce1141", "#002B5C", "#002b5c")); ggplotly()

ggplot(data=post_trade, aes(x=reorder(trade_comp, -avg_fppg), y=avg_fppg, fill=trade_comp)) +
  geom_bar(stat="identity", width=0.6, colour="black") +
  theme_bw() + theme(axis.title.x=element_blank(), axis.title.y=element_blank()) +
  geom_text(aes(label = fr_players), size = 3, colour="white", fontface="bold", hjust = 0.5, vjust = 3) +
  labs(title = "Franchise NBA Rankings - Avg Fantasy Points Per Player (HT 2019 Stats - After)", 
       fill = "Franchise Team") +
  scale_fill_manual(values=c("#C8102E", "#061922", "#008348", "#00788C", "#ce1141", 
                             "#860038", "#007dc5", "#0E2240", "#C8102E", "#1D428A",
                             "#ce1141", "#ffc633", "#1D428A", "#552582", "#5D76A9", 
                             "#98002e", "#00471b", "#78be20", "#b6995a", "#F58426",
                             "#EF3B24", "#007dc5", "#006bb6", "#e56020", "#000000", 
                             "#724c9f", "#bac3c9", "#ce1141", "#002B5C", "#002b5c")); ggplotly()

```

```{r per-week-scores, fig.width=12, fig.height=10, warning=FALSE}

# regular season 
week1_totals <- select_data %>% group_by(trade_comp) %>% 
  top_n(n = 15, wt = fntx_fppg) %>% summarise(week1_totals = sum(week1_totals)) 
week2_totals <- select_data %>% group_by(trade_comp) %>% 
  top_n(n = 15, wt = fntx_fppg) %>% summarise(week2_totals = sum(week2_totals)) 
week3_totals <- select_data %>% group_by(trade_comp) %>% 
  top_n(n = 15, wt = fntx_fppg) %>% summarise(week3_totals = sum(week3_totals)) 
week4_totals <- select_data %>% group_by(trade_comp) %>% 
  top_n(n = 15, wt = fntx_fppg) %>% summarise(week4_totals = sum(week4_totals)) 
week5_totals <- select_data %>% group_by(trade_comp) %>% 
  top_n(n = 15, wt = fntx_fppg) %>% summarise(week5_totals = sum(week5_totals)) 
week6_totals <- select_data %>% group_by(trade_comp) %>% 
  top_n(n = 15, wt = fntx_fppg) %>% summarise(week6_totals = sum(week6_totals)) 
week7_totals <- select_data %>% group_by(trade_comp) %>% 
  top_n(n = 15, wt = fntx_fppg) %>% summarise(week7_totals = sum(week7_totals)) 
week8_totals <- select_data %>% group_by(trade_comp) %>% 
  top_n(n = 15, wt = fntx_fppg) %>% summarise(week8_totals = sum(week8_totals)) 
week9_totals <- select_data %>% group_by(trade_comp) %>% 
  top_n(n = 15, wt = fntx_fppg) %>% summarise(week9_totals = sum(week9_totals))
week10_totals <- select_data %>% group_by(trade_comp) %>% 
  top_n(n = 15, wt = fntx_fppg) %>% summarise(week10totals = sum(week10_totals))
week11_totals <- select_data %>% group_by(trade_comp) %>% 
  top_n(n = 15, wt = fntx_fppg) %>% summarise(week11_totals = sum(week11_totals)) 
week12_totals <- select_data %>% group_by(trade_comp) %>% 
  top_n(n = 15, wt = fntx_fppg) %>% summarise(week12_totals = sum(week12_totals)) 
week13_totals <- select_data %>% group_by(trade_comp) %>% 
  top_n(n = 15, wt = fntx_fppg) %>% summarise(week13_totals = sum(week13_totals)) 
week14_totals <- select_data %>% group_by(trade_comp) %>% 
  top_n(n = 15, wt = fntx_fppg) %>% summarise(week14_totals = sum(week14_totals)) 
week15_totals <- select_data %>% group_by(trade_comp) %>% 
  top_n(n = 15, wt = fntx_fppg) %>% summarise(week15_totals = sum(week15_totals)) 
week16_totals <- select_data %>% group_by(trade_comp) %>% 
  top_n(n = 15, wt = fntx_fppg) %>% summarise(week16_totals = sum(week16_totals)) 
week17_totals <- select_data %>% group_by(trade_comp) %>% 
  top_n(n = 15, wt = fntx_fppg) %>% summarise(week17_totals = sum(week17_totals)) 
week18_totals <- select_data %>% group_by(trade_comp) %>% 
  top_n(n = 15, wt = fntx_fppg) %>% summarise(week18_totals = sum(week18_totals)) 
week19_totals <- select_data %>% group_by(trade_comp) %>% 
  top_n(n = 15, wt = fntx_fppg) %>% summarise(week19_totals = sum(week19_totals))

# playoff totals by team 
playoff1_totals <- select_data %>% group_by(trade_comp) %>% summarise(playoff1_totals = sum(playoff1_totals))
playoff2_totals <- select_data %>% group_by(trade_comp) %>% summarise(playoff2_totals = sum(playoff2_totals))
playoff3_totals <- select_data %>% group_by(trade_comp) %>% summarise(playoff3_totals = sum(playoff3_totals))
playoff4_totals <- select_data %>% group_by(trade_comp) %>% summarise(playoff4_totals = sum(playoff4_totals))

weekly_totals <- right_join(week1_totals,week2_totals, by = "trade_comp") %>% 
  right_join(week3_totals, by = "trade_comp") %>% 
  right_join(week4_totals, by = "trade_comp") %>% 
  right_join(week5_totals, by = "trade_comp") %>% 
  right_join(week6_totals, by = "trade_comp") %>% 
  right_join(week7_totals, by = "trade_comp") %>% 
  right_join(week8_totals, by = "trade_comp") %>% 
  right_join(week9_totals, by = "trade_comp") %>%
  right_join(week10_totals, by = "trade_comp") %>%
  right_join(week11_totals, by = "trade_comp") %>%
  right_join(week12_totals, by = "trade_comp") %>% 
  right_join(week13_totals, by = "trade_comp") %>% 
  right_join(week14_totals, by = "trade_comp") %>% 
  right_join(week15_totals, by = "trade_comp") %>% 
  right_join(week16_totals, by = "trade_comp") %>% 
  right_join(week17_totals, by = "trade_comp") %>% 
  right_join(week18_totals, by = "trade_comp") %>% 
  right_join(week19_totals, by = "trade_comp") %>% 
  right_join(playoff1_totals, by = "trade_comp") %>% 
  right_join(playoff2_totals, by = "trade_comp") %>% 
  right_join(playoff3_totals, by = "trade_comp") %>% 
  right_join(playoff4_totals, by = "trade_comp")  

rm(week1_totals,week2_totals,week3_totals,week4_totals,
   week5_totals,week6_totals,week7_totals,week8_totals,week9_totals,
  week10_totals,week11_totals,week12_totals,week13_totals,week14_totals,
   week15_totals,week16_totals,week17_totals,week18_totals,week19_totals,
   playoff1_totals,playoff2_totals,playoff3_totals,playoff4_totals)


weekly_totals <- as_tibble(t(weekly_totals)) 
colnames(weekly_totals) <- as.matrix(weekly_totals[1,])
weekly_totals <- weekly_totals[-1,]
week <- as_tibble(c("1","2","3","4","5","6","7","8","9",
                    "10", "11", "12", "13", "14", "15", 
                    "16", "17", "18", "19", "20", "21", "22", "23"))
weekly_totals <- weekly_totals %>% bind_cols(week) %>% rename(week = "value")
weekly_totals <- as_tibble(sapply(weekly_totals, as.numeric ))
weekly_totals <- weekly_totals %>% select(week, everything()); rm(week)
class(weekly_totals)

weekly_totals_plot <- weekly_totals %>% 
  filter(week > 10 & week < 20) %>% # games that have passed in regular season 
  #filter(week > 19 & week < 24) %>% # playoff filter 
  ggplot() +
  geom_line(aes(y = ATL, x = week, colour = "ATL"), group = 1) +
  geom_line(aes(y = BKN, x = week, colour = "BKN"), group = 1) +
  geom_line(aes(y = BOS, x = week, colour = "BOS"), group = 1) +
  geom_line(aes(y = CHA, x = week, colour = "CHA"), group = 1) +
  geom_line(aes(y = CHI, x = week, colour = "CHI"), group = 1, size = 1.2) + # pick 
  geom_line(aes(y = CLE, x = week, colour = "CLE"), group = 1, size = 1.2) + # pick 
  geom_line(aes(y = DAL, x = week, colour = "DAL"), group = 1) +
  geom_line(aes(y = DEN, x = week, colour = "DEN"), group = 1) +
  geom_line(aes(y = DET, x = week, colour = "DET"), group = 1) +
  geom_line(aes(y = GSW, x = week, colour = "GSW"), group = 1) +
  geom_line(aes(y = HOU, x = week, colour = "HOU"), group = 1) +
  geom_line(aes(y = IND, x = week, colour = "IND"), group = 1, size = 1.2) + # pick 
  geom_line(aes(y = LAC, x = week, colour = "LAC"), group = 1) +
  geom_line(aes(y = LAL, x = week, colour = "LAL"), group = 1) +
  geom_line(aes(y = MEM, x = week, colour = "MEM"), group = 1) +
  geom_line(aes(y = MIA, x = week, colour = "MIA"), group = 1) +
  geom_line(aes(y = MIL, x = week, colour = "MIL"), group = 1) +
  geom_line(aes(y = MIN, x = week, colour = "MIN"), group = 1) +
  geom_line(aes(y = NOP, x = week, colour = "NOP"), group = 1, size = 1.2) + # pick 
  geom_line(aes(y = NYK, x = week, colour = "NYK"), group = 1) +
  geom_line(aes(y = OKC, x = week, colour = "OKC"), group = 1) +
  geom_line(aes(y = ORL, x = week, colour = "ORL"), group = 1, size = 1.2) + # pick 
  geom_line(aes(y = PHI, x = week, colour = "PHI"), group = 1) +
  geom_line(aes(y = PHX, x = week, colour = "PHX"), group = 1) +
  geom_line(aes(y = POR, x = week, colour = "POR"), group = 1) +
  geom_line(aes(y = SAC, x = week, colour = "SAC"), group = 1) + 
  geom_line(aes(y = SAS, x = week, colour = "SAS"), group = 1) +
  geom_line(aes(y = TOR, x = week, colour = "TOR"), group = 1) +
  geom_line(aes(y = UTA, x = week, colour = "UTA"), group = 1) +
  geom_line(aes(y = WAS, x = week, colour = "WAS"), group = 1, size = 1.2) + # pick 
  labs(title = "Projected Weekly Totals in Franchise") + 
  scale_color_manual(values=c("#C8102E", "#061922", "#008348", "#00788C", "#ce1141", 
                             "#860038", "#007dc5", "#0E2240", "#C8102E", "#1D428A",
                             "#ce1141", "#ffc633", "#1D428A", "#552582", "#5D76A9", 
                             "#98002e", "#00471b", "#78be20", "#b6995a", "#F58426",
                             "#EF3B24", "#007dc5", "#006bb6", "#e56020", "#000000", 
                             "#724c9f", "#bac3c9", "#ce1141", "#002B5C", "#002b5c")) +
  #scale_x_discrete(breaks=seq()) +
  theme(axis.title.x = element_blank(), axis.ticks.x = element_blank(),
        axis.title.y = element_blank(), legend.title = element_blank()); ggplotly()
```




































