---
title: "GSD2 In-Season Tools"
author: "Brandon L. Kramer"
date: "12/24/2019"
output: html_document
---

```{r pull packages and projection data, include=FALSE}
#install.packages("tidyverse"); install.packages("googlesheets")
rm(list = ls())
for (pkg in c("googledrive", "googlesheets4", "tidyverse", "plotly")) {library(pkg, character.only = TRUE)}

setwd("C:/Users/bkram/CloudStation/NBA/data")
botb_contracts <- read_csv("nba_fantasy_data - botb_contracts.csv")
gsd2_contracts <- read_csv("nba_fantasy_data - gsd2_contracts.csv")
franchise_contracts <- read_csv("nba_fantasy_data - franchise_contracts.csv")
legacy_contracts <- read_csv("nba_fantasy_data - legacy_contracts.csv")
bballref18 <- read_csv("nba_fantasy_data - bballref18.csv")
hashalt19 <- read_csv("nba_fantasy_data - 2019_hashtag_alt_proj.csv")
hashtag19 <- read_csv("nba_fantasy_data - 2019_hashtag_proj.csv")
gsd2_inseason <- read_csv("nba_fantasy_data - gsd2_inseason.csv")
nba_schedule <- read_csv("nba_fantasy_data - 2019_nba_schedule.csv")

bballref18$player <- bballref18$player %>% 
  str_replace_all(c('Á' = 'A', 'ā' = 'a', 'á' = 'a', 'č' = 'c', 'ć' = 'c', 'è' = 'e', 
                    'é' = 'e', 'ê' = 'e', 'ić' = 'ic', 'ö' = 'o', 'ó' = 'o', 'Š' = 'S', 
                    'š' = 's', 'ū' = 'u', 'ý' = 'y', 'Ž' = 'Z', 'ž' = 'z', 'Élie' = 'Elie',
                    'P.J.' = 'PJ','C.J.' = 'CJ', 'R.J.' = 'RJ', 'T.J.' = 'TJ', 'D.J.' = 'DJ', 
                    'J.J.' = 'JJ', 'Dončić' = 'Doncic', "Demarre" = "DeMarre",
                    'Louis' = 'Lou', 'Edrice' = 'Bam', 'Waller-Prince' = 'Prince', "O.G." = "OG", 
                    'Jaren Jackson' = 'Jaren Jackson Jr.','Kelly Oubre' = 'Kelly Oubre Jr.', 
                    'Marvin Bagley' = 'Marvin Bagley III', 'Otto Porter' = 'Otto Porter Jr.', 
                    'Wendell Carter' = 'Wendell Carter Jr.', 'Larry Nance' = 'Larry Nance Jr.',
                    'Walt Lemon' = 'Walt Lemon Jr.', 'Dennis Schröder' = 'Dennis Schroder', 
                    'Tim Hardaway' = 'Tim Hardaway Jr.'))

combined_data <- bballref18 %>% 
  rename(bbr_pts = "PTS", bbr_dreb = "DRB", bbr_orb = "ORB",
         bbr_ast = "AST", bbr_stl = "STL", bbr_blk = "BLK",
         bbr_tov = "TOV", bbr_threes = "3P", bbr_fga = "FGA",
         bbr_fgm = "FG", bbr_ftm = "FT",  bbr_fta = "FTA", bbr_gms = "G", bbr_mpg = "MP", age = "Age") %>%
  mutate(bbr_ld_fpts = bbr_pts + (bbr_dreb*1.5) + (bbr_orb*2) + (bbr_ast*2) + (bbr_stl*2.5) + (bbr_blk*2.5) +
         (bbr_tov*-1) + bbr_threes + (bbr_fga*-0.5) + (bbr_fgm*0.5) + bbr_ftm + (bbr_fta*-1)) %>%
  mutate(bbr_gsd2_fpts = bbr_pts + (bbr_dreb*1.5) + (bbr_orb*2) + (bbr_ast*2) + (bbr_stl*2.5) + (bbr_blk*2.5) +
         (bbr_tov*-1) + bbr_threes + (bbr_fga*-0.5) + (bbr_fgm*0.5) + bbr_ftm + (bbr_fta*-1)) %>% 
  mutate(bbr_gsd2_fpts = bbr_pts + bbr_dreb + (bbr_orb*1.25) + (bbr_ast*1.5) + (bbr_stl*1.5) + (bbr_blk*2) +
         (bbr_tov*-1)+bbr_threes+(bbr_fga*-0.5)+(bbr_fgm*0.5)+(bbr_ftm*0.5)+(bbr_fta*-0.75)) %>%
  mutate(bbr_botb_fpts = bbr_pts + bbr_dreb + (bbr_orb*1.25) + (bbr_ast*1.5) + (bbr_stl*1.5) + (bbr_blk*2) +
         (bbr_tov*-1)+bbr_threes+(bbr_fga*-0.5)+(bbr_fgm*0.5)+(bbr_ftm*0.5)+(bbr_fta*-0.75)) %>% 
  select(player, age, bbr_ld_fpts, bbr_gsd2_fpts, bbr_gsd2_fpts, bbr_botb_fpts, bbr_gms, bbr_mpg,
         bbr_pts, bbr_dreb, bbr_orb, bbr_ast, bbr_stl, bbr_blk, bbr_tov, bbr_threes, bbr_fga, bbr_fgm, bbr_ftm, bbr_fta)

hashalt19$player <- hashalt19$player %>% 
  str_replace_all(c('Á' = 'A', 'ā' = 'a', 'á' = 'a', 'č' = 'c', 'ć' = 'c', 'è' = 'e', 'é' = 'e', 'ê' = 'e',
                    'ö' = 'o', 'ó' = 'o', 'Š' = 'S', 'š' = 's', 'ū' = 'u', 'ý' = 'y', 'Ž' = 'Z', 'ž' = 'z',
                    'P.J.' = 'PJ','C.J.' = 'CJ', 'R.J.' = 'RJ', 'T.J.' = 'TJ', 'D.J.' = 'DJ', 'J.J.' = 'JJ',
                    'Louis' = 'Lou', 'Edrice' = 'Bam', 'Waller-Prince' = 'Prince', "O.G." = "OG", 
                    'Jaren Jackson' = 'Jaren Jackson Jr.','Kelly Oubre' = 'Kelly Oubre Jr.', 
                    'Marvin Bagley' = 'Marvin Bagley III', 'Otto Porter' = 'Otto Porter Jr.', 
                    'Wendell Carter' = 'Wendell Carter Jr.', 'Larry Nance' = 'Larry Nance Jr.',
                    'Walt Lemon' = 'Walt Lemon Jr.', 'Dennis Schröder' = 'Dennis Schroder', 
                    'Tim Hardaway' = 'Tim Hardaway Jr.', "Demarre" = "DeMarre"))

hashalt19 <- hashalt19 %>% 
  rename(hta_pts = "PTS", hta_treb = "REB", hta_ast = "AST", hta_stl = "STL", hta_blk = "BLK",
         hta_tov = "TOV", hta_threes = "THREES", hta_fga = "FGA",hta_fgm = "FGM", hta_ftm = "FTM",  
         hta_fta = "FTA", hta_mpg = "MPG", hta_ftp = "FT", hta_gms = "Gs") %>%
  mutate(hta_dreb = hta_treb*0.78) %>% 
  mutate(hta_orb = hta_treb*0.22) %>% 
  mutate(hta_ld_fpts = hta_pts + (hta_dreb*1.5) + (hta_orb*2) + (hta_ast*2) + (hta_stl*2.5) + (hta_blk*2.5) +
         (hta_tov*-1) + hta_threes + (hta_fga*-0.5) + (hta_fgm*0.5) + hta_ftm + (hta_fta*-1)) %>%
  mutate(hta_gsd2_fpts = hta_pts + (hta_dreb*1.5) + (hta_orb*2) + (hta_ast*2) + (hta_stl*2.5) + (hta_blk*2.5) +
         (hta_tov*-1) + hta_threes + (hta_fga*-0.5) + (hta_fgm*0.5) + hta_ftm + (hta_fta*-1)) %>% 
  mutate(hta_gsd2_fpts = hta_pts + hta_dreb + (hta_orb*1.25) + (hta_ast*1.5) + (hta_stl*1.5) + (hta_blk*2) +
         (hta_tov*-1)+hta_threes+(hta_fga*-0.5)+(hta_fgm*0.5)+(hta_ftm*0.5)+(hta_fta*-0.75)) %>%
  mutate(hta_botb_fpts = hta_pts + hta_dreb + (hta_orb*1.25) + (hta_ast*1.5) + (hta_stl*1.5) + (hta_blk*2) +
         (hta_tov*-1)+hta_threes+(hta_fga*-0.5)+(hta_fgm*0.5)+(hta_ftm*0.5)+(hta_fta*-0.75)) %>% 
  select(player, hta_ld_fpts, hta_gsd2_fpts, hta_gsd2_fpts, hta_botb_fpts, hta_gms, hta_mpg, 
         hta_pts, hta_dreb, hta_orb, hta_ast, hta_stl, hta_blk, hta_tov, hta_threes, hta_fga, hta_fgm, hta_ftm, hta_fta, hta_ftp)
  
combined_data <- combined_data %>% 
  full_join(hashalt19, by = "player")

hashtag19$player <- hashtag19$player %>% 
  str_replace_all(c('Á' = 'A', 'ā' = 'a', 'á' = 'a', 'č' = 'c', 'ć' = 'c', 'è' = 'e', 'é' = 'e', 'ê' = 'e',
                    'ö' = 'o', 'ó' = 'o', 'Š' = 'S', 'š' = 's', 'ū' = 'u', 'ý' = 'y', 'Ž' = 'Z', 'ž' = 'z',
                    'P.J.' = 'PJ','C.J.' = 'CJ', 'R.J.' = 'RJ', 'T.J.' = 'TJ', 'D.J.' = 'DJ', 'J.J.' = 'JJ',
                    'Louis' = 'Lou', 'Edrice' = 'Bam', 'Waller-Prince' = 'Prince', "O.G." = "OG", 
                    "Demarre" = "DeMarre", 'Dennis Schröder' = 'Dennis Schroder'))

hashtag19 <- hashtag19 %>% 
  rename(ht_pts = "PTS", ht_dreb = "DREB", ht_orb = "OREB", ht_ast = "AST", ht_stl = "STL", ht_blk = "BLK",
         ht_tov = "TO", ht_threes = "THREES", ht_fga = "FGA", ht_fgm = "FGM", ht_ftm = "FTM",  
         ht_fta = "FTA", ht_mpg = "MPG", ht_gms = "GP", ht_fgp = "FG%", ht_ftp = "FT%") %>%
  mutate(ht_ld_fpts = ht_pts + (ht_dreb*1.5) + (ht_orb*2) + (ht_ast*2) + (ht_stl*2.5) + (ht_blk*2.5) +
         (ht_tov*-1) + ht_threes + (ht_fga*-0.5) + (ht_fgm*0.5) + ht_ftm + (ht_fta*-1)) %>%
  mutate(ht_gsd2_fpts = ht_pts + (ht_dreb*1.5) + (ht_orb*2) + (ht_ast*2) + (ht_stl*2.5) + (ht_blk*2.5) +
         (ht_tov*-1) + ht_threes + (ht_fga*-0.5) + (ht_fgm*0.5) + ht_ftm + (ht_fta*-1)) %>% 
  mutate(ht_gsd2_fpts = ht_pts + ht_dreb + (ht_orb*1.25) + (ht_ast*1.5) + (ht_stl*1.5) + (ht_blk*2) +
         (ht_tov*-1)+ht_threes+(ht_fga*-0.5)+(ht_fgm*0.5)+(ht_ftm*0.5)+(ht_fta*-0.75)) %>%
  mutate(ht_botb_fpts = ht_pts + ht_dreb + (ht_orb*1.25) + (ht_ast*1.5) + (ht_stl*1.5) + (ht_blk*2) +
         (ht_tov*-1)+ht_threes+(ht_fga*-0.5)+(ht_fgm*0.5)+(ht_ftm*0.5)+(ht_fta*-0.75)) %>% 
  select(player, ht_ld_fpts, ht_gsd2_fpts, ht_gsd2_fpts, ht_botb_fpts, ht_gms, ht_mpg, 
         ht_pts, ht_dreb, ht_orb, ht_ast, ht_stl, ht_blk, ht_tov, ht_threes, ht_fga, ht_fgm, ht_fgp, ht_ftm, ht_fta, ht_ftp)

combined_data <- combined_data %>% 
  full_join(hashtag19, by = "player")

gsd2_contracts$player <- gsd2_contracts$player %>% 
  str_replace_all(c('C.J.' = 'CJ', 'R.J.' = 'RJ', 'T.J.' = 'TJ', 'D.J.' = 'DJ', "O.G." = "OG", 
                    'Louis' = 'Lou', 'Edrice' = 'Bam', 'Waller-Prince' = 'Prince', "Demarre" = "DeMarre",
                    'Á' = 'A', 'ā' = 'a', 'á' = 'a', 'č' = 'c', 'ć' = 'c', 'è' = 'e', 'é' = 'e', 'ê' = 'e',
                    'ö' = 'o', 'ó' = 'o', 'Š' = 'S', 'š' = 's', 'ū' = 'u', 'ý' = 'y', 'Ž' = 'Z', 'ž' = 'z',
                    'P.J.' = 'PJ','C.J.' = 'CJ', 'R.J.' = 'RJ', 'T.J' = 'TJ', 'D.J.' = 'DJ', 'J.J.' = 'JJ'))

combined_data <- combined_data %>% 
  full_join(gsd2_contracts, by = "player") %>% select(-gsd2_team)

# in-season fantrax 

gsd2_inseason$player <- gsd2_inseason$Player %>% 
  str_replace_all(c('Á' = 'A', 'ā' = 'a', 'á' = 'a', 'č' = 'c', 'ć' = 'c', 'è' = 'e', 'é' = 'e', 'ê' = 'e',
                    'ö' = 'o', 'ó' = 'o', 'Š' = 'S', 'š' = 's', 'ū' = 'u', 'ý' = 'y', 'Ž' = 'Z', 'ž' = 'z',
                    'P.J.' = 'PJ','C.J.' = 'CJ', 'R.J.' = 'RJ', 'T.J.' = 'TJ', 'D.J.' = 'DJ', 'J.J.' = 'JJ',
                    'Louis' = 'Lou', 'Edrice' = 'Bam', 'Waller-Prince' = 'Prince', "O.G." = "OG", 
                    'Walt Lemon' = 'Walt Lemon Jr.', 'Dennis Schröder' = 'Dennis Schroder', "Demarre" = "DeMarre"))

gsd2_inseason <- gsd2_inseason %>% 
  rename(
         #trade_comp = "Trade",
          fntx_gms = "GP", fntx_fppg = "FP/G", gsd2_team = "Status", position = "Position") %>%
  rename(nba_team = "Team") %>% 
  mutate(nba_team = recode(nba_team, PHO = "PHX", SA = "SAS", NY = "NYK", NO = "NOP", GS = "GSW")) %>% 
  select(player, fntx_fppg, fntx_gms, gsd2_team, nba_team, position)
         
select_data <- combined_data %>% 
  inner_join(gsd2_inseason, by = "player") %>% 
  select(player, age, fntx_fppg, bbr_gsd2_fpts, hta_gsd2_fpts, ht_gsd2_fpts, 
         bbr_gms, bbr_mpg, hta_gms, hta_mpg, ht_gms, ht_mpg,
         gsd2_team, gsd2_2019, gsd2_2020, gsd2_2021, gsd2_2022, gsd2_2023, gsd2_2024, 
         trade_comp, 
         gsd2_rfa, gsd2_gleague, gsd2_intl, nba_team, position) %>%   
  inner_join(nba_schedule, by = "nba_team") 
  #mutate(playoff1 = week20,playoff2 = week21,playoff3 = week22,playoff4 = week23) %>% 
  # regular season schedule 
  #mutate(week1_totals = (fntx_fppg * week1)) %>%
  #mutate(week2_totals = (fntx_fppg * week2)) %>%
  #mutate(week3_totals = (fntx_fppg * week3)) %>%
  #mutate(week4_totals = (fntx_fppg * week4)) %>%
  #mutate(week5_totals = (fntx_fppg * week5)) %>%
  #mutate(week6_totals = (fntx_fppg * week6)) %>%
  #mutate(week7_totals = (fntx_fppg * week7)) %>%
  #mutate(week8_totals = (fntx_fppg * week8)) %>%
  #mutate(week9_totals = (fntx_fppg * week9)) %>% 
  #mutate(week10_totals = (fntx_fppg * week10)) %>%  
  #mutate(week11_totals = (fntx_fppg * week11)) %>%
  #mutate(week12_totals = (fntx_fppg * week12)) %>%
  #mutate(week13_totals = (fntx_fppg * week13)) %>%
  #mutate(week14_totals = (fntx_fppg * week14)) %>%
  #mutate(week15_totals = (fntx_fppg * week15)) %>%
  #mutate(week16_totals = (fntx_fppg * week16)) %>%
  #mutate(week17_totals = (fntx_fppg * week17)) %>%
  #mutate(week18_totals = (fntx_fppg * week18)) %>%
  #mutate(week19_totals = (fntx_fppg * week19)) %>%
  # playoff totals 
  #mutate(playoff1_totals = (fntx_fppg * playoff1)) %>%
  #mutate(playoff2_totals = (fntx_fppg * playoff2)) %>%
  #mutate(playoff3_totals = (fntx_fppg * playoff3)) %>%
  #mutate(playoff4_totals = (fntx_fppg * playoff4)) %>% 
  #filter(player != "Rodions Kurucs" & player != "Jontay Porter" & player != "Chimezie Metu" & player != "Issuf Sanon" &
  #       player != "Dewan Hernandez" & player != "Ognen Jaramaz" & player != "Marial Shayok" & player != "Justin James" &
  #       player != "Didi Louzada Silva" &  player != "Alessandro Gentile" ) 
  
rm(bballref18, hashtag19, hashalt19, franchise_contracts, gsd2_contracts, legacy_contracts, botb_contracts)
```

```{r looking at overall projections}
select_data %>% 
  #filter(player == "Skal Labissiere") %>% # by player
  filter(gsd2_team == "DAL") %>% 
  #filter(bbr_gms > 50) %>%        # by games played
  #filter(bbr_gsd2_fpts > 25) %>%    # by 2018 stats
  #filter(hta_gsd2_fpts > 25) %>%    # by hta projections 
  #filter(ht_gsd2_fpts > 25) %>%     # by ht projections 
  #filter(age < 25) %>%            # by age 
  #arrange(-bbr_gsd2_fpts) %>%       # arrange by 2018 stats
  #arrange(-hta_gsd2_fpts) %>%       # arrange by hta projections
  arrange(-fntx_fppg) %>%         # arrange by ht projections
  select(player, age, fntx_fppg, position, gsd2_2019, gsd2_2020, gsd2_2021, gsd2_rfa, 
         bbr_gsd2_fpts, hta_gsd2_fpts, ht_gsd2_fpts,  gsd2_gleague, gsd2_intl)
```

# Value Calculators 

```{r hashtag evaluations in fr}
select_data %>% 
  mutate(fntx_value_19 = fntx_fppg / gsd2_2019 * 10000) %>% 
  mutate(fntx_value_20 = fntx_fppg / gsd2_2020 * 10000) %>%
  mutate(fntx_value_21 = fntx_fppg / gsd2_2021 * 10000) %>%
  mutate(diff = fntx_fppg - ht_gsd2_fpts) %>%
  filter(fntx_fppg > 25) %>% 
  filter(gsd2_team == "POR" | gsd2_team == "MIN" | gsd2_team == "BOS" | gsd2_team == "GSW" |  
         gsd2_team == "NOP" | gsd2_team == "CHI" | gsd2_team == "PHI" | gsd2_team == "CHA" | 
         gsd2_team == "ORL" | gsd2_team == "MIL" | gsd2_team == "DET" | gsd2_team == "OKC"  
  ) %>%
  #filter(gsd2_team == "CLE") %>% 
  #filter(age < 25) %>% 
  filter(grepl("PG", position)) %>% 
  arrange(-fntx_value_19) %>% 
  select(player, age, gsd2_team, fntx_fppg, position, ht_gsd2_fpts, diff, fntx_value_19, fntx_value_20, 
         gsd2_2019, gsd2_2020, gsd2_2021, gsd2_rfa, gsd2_gleague, gsd2_intl)
```

